/**
 * Created by senlin.ouyang on 2015/7/15.
 */
uc_resource = {
    Common: {
        OK: "OK",
        Cancel: "Cancel",
        Message: "Message",
        Contact: "Address Book",
        Meeting: "Calendar",
        App: "Application",
        Success: "Success",
        Save: "Save",
        Known: "Understand",
        Prompt: "Notification",
        Cut: "Cut",
        Copy: "Copy",
        Paste: "Paste",
        SaveAs: "Save As",
        Open: "Open",
        Forward: "Forward",
        Notification: "Notification",
        RequestFailed: "Request Failed",
        Error: "Error",
        Cloud: "云盘",
        ReStart: "重新发起",
        ReSend: "重新发送",
        ReJoin: "重新加入",
        Ignore: "忽略",
        IgnoreAll: "忽略全部",
        Etc: "等",
        AppName: "蜜蜂",
        SuperGroup: "超",
        GNet: "云",
        Local: "地"
    },
    ClientStatus: {
        Disconnected: "Disconnected",
        Connecting: "Connecting...",
        Connected: "Connected",
        ReConnectFailed: "Reconnect Failed",
        ReConnect: "Reconnect"
    },
    WindowTitle: {
        Login: "Login",
        CreateProject: "创建项目",
        CreateGroup: "Create Group",
        CreateMeeting: "Create Meeting",
        ImagePreview: "Previe Image",
        Notification: "Notification",
        VideoPreview: "Video Preview"
    },
    Extra: {
        Microblog: "Workbook",
        Create: "Create",
        Create_2: "聊天",
        Search: "Search",
        Setting: "Setting"
    },
    Password: {
        PasswordModified: "You have updated the login password, please login again"
    },
    Login: {
        AccountPlaceHolder: "Account ID",
        PasswordPlaceHolder: "Password",
        Login: "Login",
        RememberPassword: "Remember Password",
        AutoLogin: "Auto Login",
        ForgetPassword: "Forgot Password?",
        Cancel: "Cancel",
        NeitherEmpty: "Either account ID or password can not be ignored or empty",
        Wrong: "Error",
        WrongType: "客户端类型错误",
        NotEmpty: "客户端id和mac地址不能为空",
        WrongInput: "Input Error",
        InvalidAccount: "The Account ID Is Invalid ",
        NeedURL: "用户有多个站点,客户端需要提示用户输入新的站点url重新登录",
        URLFailed: "获取站点url失败，请稍后再试",
        GetFailed: "获取站点id或客户编码失败，请稍后再试",
        QueryError: "查询用户公司类型和导入方式出错",
        DBFailed: "The Database Access Failed, Please Try Again Later",
        Authority: "The User Is Not Authorized to Access Bee",
        IDFailed: "生成resource id失败，请稍后再试",
        CheckFailed: "检查企业生态用户失败，请稍后再试",
        UserIDFailed: "通过用户id获取站点信息失败",
        InfoNotExist: "The Info You Input Is Not Existed",
        LoginFailed: "Login Failed",
        Password: "Your Password",
        Due: "Your Password Will Be Due on XX, Please Update Your Password Immediately",
        SetPassword: "Change Password",
        SetTips: "If You Don't Update Password, You Can't Login to Bee Successfully.  Are You Sure Not To Update Password Now?",
        PasswordExpired: "Your Password Has Expired, Please Update Your Password And Login Again",
        UCASFailed: "UCAS登录失败",
        DeleteAccount: "Delete Account"
    },
    Main: {
        StartChat: "Sart Chatting",
        CreateProject: "创建项目",
        CreateMeeting: "Create Meeting",
        CreateCloud: "创建文件库",
        BeeForum: "Bee Forum",
        Setting: "System Settings",
        ChatMessage: "You Don't Select Any Messages",
        MeetingMessage: "You Don't Select Any Meeting",
        ContactsMessageUser: "You Don't Select Any Contact",
        ContactsMessageProject: "You Don't Choose Any Project",
        ContactsMessageGroup: "You Don't Select Any Group",
        MeetingMinutesMessage: "There's No Any Meeting Minutes Uploaded!"
    },
    Tray: {
        Setting: "Setting",
        Logout: "Logout",
        Quit: "Quit"
    },
    Search: {
        InputPlaceHolder: "Input Keyword",
        All: "All Results",
        Contact: "Address Book",
        Meeting: "Calendar",
        Document: "Document",
        Link: "Workbook",
        Message: "Message",
        NoResult: "No Any Result Found",
        Searching: "Searching...",
        NoNetwork: "Your Device Didn't Connect to Internet, No Search Results Available",
        LoadingMore: "Loading More Result",
        LoadFailed: "Load Failed",
        NoMore: "No More Results",
        ViewMoreContact: "View More Contacts",
        ViewMoreMeeting: "View More Meetings",
        ViewMoreDocument: "View More Documents",
        ViewMoreLink: "View More Status Update on Workbook",
        ViewMoreMessage: "View More Messages",
        MeetingHostName: "Meeting Host: {1}",
        MessageCount: "{1} Messages",
        DoNotHaveContacts: "没有常用联系人",
        ViewPrevOrNext: "查看前后消息"
    },
    Message: {
        You: "You",
        SendFailed: "[Sent Failed]",
        Draft: "[Draft]",
        //OrgMessage
        DepartmentMessageName: "Department Name",
        DepartmentNameChanged: "Your Department Name Has Been Changed to [{1}]",
        DepartmentTransferred: "You Have Been Transferred to [{1}]",
        PositionChanged: "Your Position Has Been Changed to {1} ",
        EmployeeJoined: "You Have {1} Employees Joined",
        EmployeeLeft: "You Have {1} Employees Resigned",
        EmployeeRightsChanged: "Congration! You Are Department Head of {1} Now！",
        JoinCompany: "You Have Been Assigned to Cooperate with {1}",
        DepartmentParentChanged: "Your Department Has Been Transferred from {1} to {2}",
        DepartmentDeleted: "The Department {2} Under Your Department {1} Has Been Deleted",
        EmployeeJoinConfirmed: "员工入职确认消息(接受{1}入职)",
        EmployeeLeaveConfirmed: "员工离职确认消息(接受{1}入职)",
        DepartmentTransferConfirmed: "员工调用确认消息(接受{1}入职)",
        //Message
        ImageMessage: "[Image]",
        AudioMessage: "[Recorded Message]",
        VideoMessage: "[Video Message]",
        FileMessage: "[Document Name]",
        CodeMessage: "[Snippet Name]",
        CloudFileMessage: "[文件]",
        TextMessageWithSender: "{1} : {2}",
        ImageMessageWithSender: "{1} : [Image]",
        AudioMessageWithSender: "{1} : [Recorded Message]",
        VideoMessageWithSender: "{1} : [Video Message]",
        FileMessageWithSender: "{1} : [Document Name]",
        CodeMessageWithSender: "{1} : [Snippet Name]",
        CloudFileMessageWithSender: "{1} : [文件]",
        MeetingVideoMessageWithSender: "{1} : [Meeting Recordings]",
        ViewMore: "More Messages",
        Resend: "Resend",
        OpenFileFailed: "Failed to Open File",
        OpenFolder: "Open File Folder",
        UnableToDownload: "文件正在被其他程序占用，无法进行此操作，请检查关闭相应的程序后再试",
        //Group
        joinCloudItem: "您加入文件库",
        InviteMemberToGroup: "{1} Invites {2} to Join Group Discussion",
        InviteMemberToProject: "{1} Invites {2} to Join Project Discussion",
        InviteMemberToCloudFile: "{1}邀请{2}加入文件库",
        MemberExitGroup: "{1} Leaves This Group",
        MemberExitProject: "{1} Leaves This Project Discussion",
        MemberExitCloudFile: "{1}退出文件库",
        EndGroup: "{1} Close This Group",
        EndProject: "{1} Close This Project",
        EndCloudFile: "{1}结束了文件库",
        KickMemberFromGroup: "{1}将{2}移出群聊",
        KickMemberFromProject: "{1}将{2}移出项目组",
        KickMemberFromCloudFile: "{1}将{2}移出文件库",
        BeKickedFromGroup: "您被{1}移出群聊",
        BeKickedFromProject: "您被{1}移出项目组",
        BeKickedFromCloudFile: "您被{1}移出文件库",
        UpdateGroupName: "{1} Have Updated The Group Name to {2}",
        UpdateProjectName: "{1}修改了项目组名称为{2}",
        UpdateCloudFileName: "{1}修改了文件库名称为{2}",
        UpdateCloudFile: "{1}上传了文件({2})",
        UpdateCloudDir: "{1}上传了文件夹({2})",
        UpdateGroupAvatar: "{1} Changed the Avatar",
        UpdateProjectAvatar: "{1}修改了项目组头像",
        UpdateCloudFileAvatar: "{1}修改了文件库头像",
        UpdateGroupDisturbState: "{1}更新了群聊免打扰设置",
        UpdateProjectDisturbState: "{1}更新了项目免打扰设置",
        UpdateGroupOnTopState: "{1}更新了群聊置顶设置",
        UpdateProjectOnTopState: "{1}更新了项目置顶设置",
        UpdateGroupReminderState: "{1}更新了群聊消息提醒设置",
        UpdateProjectReminderState: "{1}更新了项目消息提醒设置",
        UploadDocument: "{1} Upload File ({2})",
        ForwardDocument: "{1} Share File ({2})",
        DeleteDocument: "{1}Delete File ({2})",
        CommentMessage: "{1} Have Comments on ({2})",
        DisturbSetFailed: "免打扰设置失败，请稍后重试",
        //cloud
        updateDir: "{1}更新了一个文件夹",
        updateFile: "{1}更新了一个文件",
        deleteDir: "{1}刪除了一个文件夹",
        deleteFile: "{1}刪除了一个文件",
        moveDir: "{1}移动了一个文件夹",
        moveFile: "{1}移动了一个文件",
        renameDir: "{1}重命名了一个文件夹",
        renameFile: "{1}重命名了一个文件",
        //Meeting
        CreateMeetingByMe: "You Have Arranged A Recurring Meeting",
        CreateRecurrentMeetingByMe: "You Have Arranged A Meeting",
        BeInvitedToMeeting: "{1} Invites You to Join Meeting",
        BeInvitedToRecurrentMeeting: "{1} Invites You to Join The Recurring Meeting",
        AcceptMeetingInvitation: "You Have Accepted {1}'s Meeting Invitation",
        MeetingInvitationAccepted: "{1} Accept Your Meeting Invitation",
        RecurrentMeetingInvitationAccepted: "{1}Accept Your Recurring Meeting Invitation",
        RejectMeetingInvitation: "You Have Declined to Accept {1}'s Meeting Invitation",
        MeetingInvitationRejected: "{1} Decline to Accept Your Meeting Invitation",
        MeetingUpdatedByMe: "You Have Updated Meeting Information您变更了会议信息",
        MeetingUpdatedByOther: "{1} Update Meeting Information",
        MeetingForwardedByMe: "You Forward {1}'s Meeting Invitation",
        ForwardMyMeeting: "{1} Forward Your Meeting Invitation",
        ForwardMeetingToMe: "{1} Forward Meeting Inviation to You",
        CancelMeeting: "{1} Cancel Meeting Invitation",
        CreateMeetingSummary: "{1} Upload Meeting Minutes",
        updateMinutes: "{1}更新了一份会议纪要",
        AccreditMeetingByMe: "You Have Authorized {1} to Manage Your Calendar",
        AccreditMeetingToMe: "{1} Has Authorized You to Manage His/Her Calendar",
        CancelAccreditMeetingByMe: "You Have Cancelled The Calendar Authorization to {1}",
        CancelAccreditMeetingToMe: "{1} Have Cancelled the Calendar Authorization",
        JoinedInMeeting: "You Have Joined This Meeting",
        QuitMeeting: "You Have Quit This Meeting",
        sendMessageFialed: "Sent Message Failed! Please Try Again Later",
        //Open Api
        OpenApiOAMessage: "[{1}]{2}",
        OpenApiMessageTitle: "应用消息",
        MeetingVideoSuccess: "{1} Meeting Recordsing Has Completed",
        MeetingVideoWithMeetingName: "{1}'s Meeting Recordings",
        ShareMeetingVideo: "Share to Workbook",
        MeetingVideoWithSender: "{1}:[Meeting Video Recordings]",
        MeetingVideo: "[Meeting Video Recording]",
        MessageRead: "Read",
        MultiChatUnread: "{1}人未读",
        SingleChatMessageUnread: "未读",
        ConversationListLoadFailed: "消息列表加载失败,",
        ReloadConversationList: "Reload Message List",
        setMemberAdmin: "并设置为管理员",
        //Remote Assistance
        RemoteAssistanceLoading: "正在加载远程协作",
        InRemoteAssistanceForStart: "您正在进行远程协作，发起新的协作将结束原远程协作，确认发起？",
        InRemoteAssistanceForJoin: "您正在进行远程协作，加入新的协作将结束原远程协作，确认加入？",
        StartRemoteAssistanceFailed: "远程协作发起失败！",
        SendRemoteAssistanceInvitationFailed: "发送远程协作邀请失败！",
        JoinRemoteAssistanceFailed: "加入远程协作失败！",
        RemoteAssistanceEnded: "远程协作结束",
        YouAreInvitedToRemoteAssistance: "对方已开始远程协作",
        JoinRemoteAssistance: "进入协作",
        RemoteAssistanceInvited: "{1}邀请您进行远程协作",
        RemoteAssistanceAccepted: "{1}接受了您的远程协作",
        RemoteAssistanceRejected: "{1}拒绝了您的远程协作",
        //Call
        CallInvitationReceived: "{1}对你发起了一个呼叫",
        RejectedCall: "{1}拒绝了您的呼叫",
        SelfRejectedCall: "您拒绝了{1}的呼叫",
        CancelCall: "{1}取消了呼叫",
        SelfCancelCall: "您取消了对{1}的呼叫",
        SelfCancelGroupCall: "您取消了群呼",
        CallDuration: "通话时长 {1}",
        CallEndMessage: "通话结束",
        SelfRejectedFromGroupCall: "您拒绝了本次呼叫",
        RejectedGroupCall: "{1}拒绝了本次呼叫"

    },
    Chat: {
        Font: "Font Type",
        Emotion: "Emoticon",
        Image: "Image",
        File: "File",
        Code: "Snippet",
        Cloud: "云盘",
        uploadMeetingDoc: "会议资料",
        ScreenShot: "Screen Shot",
        WeekTimer: "Timer",
        ScreenTips: "Screen Shot Ctrl+Alt+A",
        ScreenHide: "Hide The Current Window When You Do Screen Shot",
        OpenImage: "Open Image",
        OpenImageDesc: "Image(*.png; *.jpg; *.bmp; *.jpeg; *.gif)",
        OpenImageTips: "*.png; *.jpg; *.bmp; *.jpeg; *.gif",
        OpenFile: "Open File",
        OpenFileDesc: "All Files(*.*)",
        DownloadFailed: "Download Failed. The File Has Been Deleted",
        SaveFiles: "Save File",
        AllFiles: "All Filed",
        SaveAs: "Save As",
        Transmit: "Forward",
        NoComments: "No Any Comments",
        ViewMore: "More Comments",
        WriteComments: "Write Comment...(1-200)",
        SendByEnter: "Send Out After Enter Key Clicked",
        SendByAltEnter: "Send Out After  Alt+Enter Clicked",
        Sending: "Sending",
        CannotSendBlank: "Can't Send Empty Message",
        Nonentity: "Not Existed",
        Open: "Open",
        OpenFailed: "Failed to Open File",
        Discuss: "Discuss",
        Collect: "Collect",
        Delete: "Delete",
        Preview: "Preview",
        Share: "Share to WeChat",
        News: "Status Update",
        Case: "Case",
        NoFiles: "No Any Files",
        LoadingFailed: "Failed to Load Page",
        Reloading: "Reloading",
        DeleteFile: "Are You Sure to Delete the File",
        Today: "Today",
        Yesterday: "Yesterday",
        CodeDesc: "Snippet Description",
        ViewDetail: "Check Details",
        ReAccept: "重新接受",
        ChooseImage: "Choose Images",
        OverSize: "The Image Size Can't Be Larger Than 5 MB, Please Choose Another Image to Upload",
        OverWidth: "The Minimum Width and Height of Image Should Be Larger Than 150 Pixels, Please Choose Another Image to Upload",
        ChooseTips: "Please Select Image",
        ScreenFaield: "Failed to Complete Screen Shot",
        ReUpload: "Upload Again",
        SaveImage: "Save Image",
        Minimize: "Minimum Size",
        Maximized: "Maximun Size",
        ExceedLimit: "The File Size You Uploaded Is Too Large您上传的文件大小超过限制！",
        BeOccupied: "The File Is Been Occuped by Other Application",
        ErrorCompulateMd5: "文件md5值计算失败！",
        ReDownload: "Download Again",
        FailedDownload: "Download Failed",
        Receive: "Receive",
        Download: "Download",
        FailUploadFile: "上传失败",
        FailUploadCancel: "取消上传",
        FailUploadDelete: "删除文件",
        ViewMeetingReport: "查看报告详情",
        MeetingReport: "会议报告",
        MessageRecord: "消息记录"
    },
    Menu: {
        Call: "Place A Call",
        ViewProfile: "Personal Profile",
        ViewCalendar: "Calendar",
        ViewMicroblog: "Workbook",
        CommonAttention: "互相关注",
        PayAttention: "Following",
        CancelAttention: "Unfollow",
        QuitProject: "Quit",
        EndProject: "Close",
        QuitGroup: "Quit",
        SetConversationOnTop: "Stick on Top",
        DeleteConversation: "Delete Conversation",
        ProjectSetting: "Setting",
        GroupSetting: "Settings",
        JoinMeeting: "Join Meeting",
        ForwardMeeting: "Forward",
        AcceptMeeting: "接受",
        RejectMeeting: "拒绝",
        RemoteAssistance: "远程协作",
        CreateMeeting: "安排会议",
        Cloud: "文件库",
        OpenCloud: "查看文件库",
        arrangeMeeting: "安排会议"
    },
    Call: {
        TextChat: "文本聊天",
        Mute: "静音",
        UnMute: "取消静音",
        OpenVideo: "打开视频",
        CloseVideo: "关闭视频",
        StartDesktopShare: "开启桌面共享",
        StopDesktopShare: "关闭桌面共享",
        SwitchAudioChanel: "切换语音",
        Invite: "邀请更多联系人",
        FullScreen: "全屏",
        QuitFullScreen: "退出全屏",
        Inviting: "等待对方接听...",
        ForYouInviting: "向你发起请求...",
        Connecting: "正在建立连接...",
        DisConnecting: "正在断开连接",
        CallTurnToEnd: "通话即将结束",
        ChooseContactsTitle: "选择成员",
        ChooseContactsPlaceHolder: "联系人名称",
        ChooseMaxContactsTips: "最多支持9人同时加入“呼”聊天",
        Retry: "重试",
        CallTelling: "呼正在进行{1}",
        SingleChatCallInvited: "呼请求...",
        GroupChatCallInvited: "邀请你加入群呼...",
        CallReply: "快速回复",
        SorryTell: "很抱歉，我现在不方便接听",
        ComeSoon: "马上到",
        CallYou: "稍后给您电话，好吗？",
        MeetingAfterCallYou: "我正在开会，稍后跟您联系",
        VoipToPhone: "当前网络状态不好，建议切换到电话",
        PhoneToVoip: "当前网络状态良好，可以切换到VOIP",
        PhoneFailed: "打电话失败，请切回VOIP",
        CloseFloatingTip: "您正在语音通话，关闭窗口会结束通话，确定关闭？",
        SelfSendMessage: "自定义...",
        TellingPhone: "正在呼叫...",
        UserBusyCall: "{1}正在通话中，请稍候再试",
        UserBusyDeleted: "{1}正在通话中，已为您去勾选，请重试邀请！",
        RejectedYourCall: "对方拒绝了你的通话邀请",
        WaitingAccepted: "待加入",
        CallRejected: "已拒绝",
        CallUserStop: "已退出",
        SelectedInvitedUser: "请选择您要添加的用户！",
        StartCallFailed: "发起呼失败，请稍后重试!",
        groupCreateCallTip: "正在努力创建连接，请稍等",
        GroupHasCall: "该讨论组正在进行一个呼叫，您是否加入？",
        InvitedUserFailed: "邀请用户加入失败，请稍候重试！",
        HasCallNotCall: "您已经有一个呼叫了，请处理后再操作！",
        MaybeHasCallNotCall: "您可能正在通话中，是否继续加入?",
        CreateCallFailed: "创建呼失败，请稍后重试！",
        SelfJoinCallFailed: "您加入呼失败！",
        leaveCallFailed: "您离开呼失败！",
        GetUserCallStatusFailed: "获取用户呼叫状态失败，请稍候重试！",
        GroupHaveCall: "该群聊有一个正在进行的的群呼，新成员会被加入该群呼，是否现在添加？",
        GroupAddMemberFailed: "该群聊有一个正在进行的的群呼,人数已达9人上限，暂时不能添加新成员",
        LongTimeNoHandle: "对方长时间未应答，可能通讯设备不在身边或离线，建议稍后重试！",
        CallQuitTip: "您正在呼中，请离开后再退出！",
        InputTelephoneNumber: "请输入电话号码",
        DialPadTrue: "确认",
        VoipCall: "网络语音",
        SelfInMeeting: "您正在会议中，请稍后重试！",
        UserInMeeting: "对方正在会议中，请稍后重试！",
        unInstallVedio: "系统没检测到音频设备，你可以</br>使用电话或安装音频设备",
        reDetection: "重新检测",
        logoutWhenCalling: "您现在正在进行语音通话，确定退出登录？",
        quitWhenCalling: "您现在正在进行语音通话，确定退出蜜蜂？",
        InputTelNumberError: "无法呼叫此号码"
    },
    Proxy: {
        ProxyAuthenticate: "代理认证",
        AccountPlaceHolder: "Account ID",
        PasswordPlaceHolder: "Password",
        NeedAccountPass: "You Can't Leave Your Account ID and Password Fields Empty"
    },
    Meeting: {
        Monday: "Monday",
        Tuesday: "Tuesday",
        Wednesday: "Wednesday",
        Thursday: "Thursday",
        Friday: "Friday",
        Saturday: "Saturday",
        Sunday: "Sunday",
        NumMonday: "一",
        NumTuesday: "二",
        NumWednesday: "三",
        NumThursday: "四",
        NumFriday: "五",
        NumSaturday: "六",
        NumSunday: "日",
        ReSunday: "Sunday",
        ReMonday: "Monday",
        ReTuesday: "Tuesday",
        ReWednesday: "Wednesday",
        ReThursday: "Thursday",
        ReFriday: "Friday",
        ReSaturday: "Saturday",
        WorkingDay: "Working Day",
        Weekday: "Sunday",
        StartTime: "Start Time",
        EndTime: "结束",
        AddMember: "添加联系人",
        AttendeeHeader: "与会者",
        HighSetting: "高级设置",
        MeetingLength: "Meeting Length",
        MeetingAttendee: "Participants",
        ScheduleTimeTooEarly: "不能安排早于当前时间的日程",
        TodayNoMeeting: "No Scheduled Meetings Today",
        TodayIsRelax: "Relax Day",
        MyCalendar: "My Calendar",
        FreeTime: "Spare Time",
        CreateCalendar: "Schedule A Meeting",
        MeetingDetail: "Details",
        MeetingChat: "Chat",
        MeetingUpload: "上传会议资料",
        MeetingUploadTip: "在这里上传会议资料",
        MeetingSummary: "Meeting Minutes",
        Members: "成员",
        OnesMeetingSummary: "'s Meeting Minutes",
        MeetingMore: "More",
        JoinMeeting: "Join Now",
        JoiningMeeting: "入会中",
        EditMeeting: "Edit",
        CancelMeeting: "Cancel",
        NewMeeting: "Arrange",
        Continue: "Continue",
        TimeZone: "Time Zone",
        DefaultCity: "Beijing",
        AllDay: "全天",
        MeetingConflict: "此会议与您的现有时间安排有冲突",
        AddMeetingAttendee: "Participants",
        SearchAttendee: "Please Input Participant's Name or Mail Address",
        MeetingPearson: "Attendees",
        MeetingLocation: "Place",
        InputLocalAddress: "Please Input The Meeting Address",
        SelectedCloudMeeting: "Use Cloud Meeting",
        MeetingComment: "Meeting Details",
        AddMeetingComment: "Add Meeting Details(Optional)",
        AddMeetingComment: "请输入备注，备注不能超过500个字",
        OthersMeetingSummary: "'s Meeting Minutes",
        AddMeetingSummary: "Add Meeting Minutes",
        FontSize: "Font Size",
        FontFamily: "Font Type",
        Section: "段落",
        YourMeeting: "Your Meeting",
        MeetingReminderBegin: "分钟后开始",
        CancelAccredit: "解除授权",
        MeetingReminderCanceled: "The Meeting Host Has Cancelled This Meeting",
        MeetingReminderTitle: "The Meeting Alert",
        SetAccredit: "You Can Authorize A Colleage to Manage Your Schedule",
        SetAccreditTitle: "Authorization",
        SetMyAccredit: "指定我的授权对象",
        CalendarAccreditSetting: "日程授权设置",
        CancelOthersAccredit: "您确定要对{1}解除日程授权吗？",
        CanceledMeeting: "Are You Sure to Cancel This Meeting?",
        RepeatChose: "Choose Again",
        RelayMeeting: "Forward Meeting",
        Rejected: "Rejected",
        Accepted: "Accepted",
        Pending: "待定",
        NoUpdateMeeting: "You Didn't Change Meeting Schedule or Attendees, You Don't Need To Update Meeting",
        AddForwardUser: "Please Add Contacts You Would Like to Forward",
        NotForwardRepeat: "您转发的参会人已经在这场会议中了！",
        UpdateMeeting: "Update Meeting",
        OthersMeeting: "{1}'s Meeting",
        InputTime: "Input Time",
        ChoseMeetingTimeLength: "Input Time Length",
        CreateMeetingIllegal: "There Are Some Problems About The Meeting You Arranged.  Want to Send Anyway?",
        NoInputLocation: "No Meeting Address",
        InputMeetingTitle: "Please Input Meeting Title",
        MeetingTimeTips: "会议开始时间不能小于当前时间",
        GNetStartTime: "开始时间不能早于当前时间。您也可以设定开始时间为当前时间，是否设置为当前时间？",
        GNetTime: "会议的结束时间不能早于开始时间",
        GNetTimeEqual: "The Meeting Start Time Is The Same as Meeting Finish Time.  You Can't Create This Meeting",
        GNetMeetingTime: "会议时长不能超过24小时",
        Minutes: "Minutes",
        Hour: "Hours",
        Canceled: "Cancelled",
        Reject: "Reject",
        Accept: "Accept",
        Today: "Today",
        Tomorrow: "Tomorrow",
        Yesterday: "Yesterday",
        NoRightCheckMeeting: "授权人已经取消了日程授权，查看不到会议信息",
        OthersCalendar: "{1}'s Schedule",
        NoMeetingMayBeCanceled: "Can't Find This Meeting.  Probably You Have Rejected This Meeting Or This Meeting Has Been Cancelled.",
        CreateSummaryDate: "Create Date",
        UpdateSummaryDate: "Update Date",
        HostPassword: "Host Password",
        AttendeePassword: "Attendee Password",
        MeetingPassword: "Meeting Passcode",
        OthersAddSummary: "Meeting Minutes Added by Others",
        MeetingVideo: "'s Meeting Recordings",
        CopyHostPassword: "复制",
        CopyAttendeePassword: "复制",
        InputMeetingSummaryContext: "Input Meeting Minutes",
        SaveMeetingSummaryFailed: "Failed to Save Meeting Minutes",
        JoinMeetingFailed: "Failed to Join Meeting",
        MeetingLocked: "Meeting Locked! Failed to Join Meeting.",
        NoticeInMeeting: "正在会议中，您真的要退出吗？",
        Year: "Year",
        Month: "Month",
        Day: "Date",
        UserName: "Name",
        Department: "Department",
        MoreSearchCheck: "More",
        TurnOn: "On",
        TurnOff: "Off",
        CreateMeetingTimeZone: [{text: "(UTC-12:00)国际日期变更线西", value: "-12"},
            {text: "(UTC-11:00)协调世界时-11", value: "-11"},
            {text: "(UTC-10:00)Hawaii", value: "-10"},
            {text: "(UTC-09:00)Alaska", value: "-9"},
            {text: "(UTC-08:00)Pacific Time(美国和加拿大)", value: "-8"},
            {text: "(UTC-08:00)Baja California", value: "-8"},
            {text: "(UTC-07:00)Chihuahua，拉巴斯，马萨特兰", value: "-7"},
            {text: "(UTC-07:00)Mountain Time(USA & Canada)", value: "-7"},
            {text: "(UTC-07:00)Arizona", value: "-7"},
            {text: "(UTC-06:00)Guadalajara，Mexico，Monterey", value: "-6"},
            {text: "(UTC-06:00)Saskatchewan", value: "-6"},
            {text: "(UTC-06:00)中部时间(美国和加拿大)", value: "-6"},
            {text: "(UTC-06:00)中美洲", value: "-6"},
            {text: "(UTC-05:00)波哥大，利马，基多", value: "-5"},
            {text: "(UTC-05:00)Eastern Time(USA & Canada)", value: "-5"},
            {text: "(UTC-05:00)Indiana(Eastern Time)", value: "-5"},
            {text: "(UTC-04:30)Caracas", value: "-4.5"},
            {text: "(UTC-04:00)Atlantic Standard Time(Canada)", value: "-4"},
            {text: "(UTC-04:00)Cuiaba，乔治敦，拉巴斯，马瑙斯", value: "-4"},
            {text: "(UTC-04:00)San Juan，San Diego，Asyncion", value: "-4"},
            {text: "(UTC-03:30)New Foundland", value: "-3.5"},
            {text: "(UTC-03:00)Brasilia", value: "-3"},
            {text: "(UTC-03:00)Buenos Aires", value: "-3"},
            {text: "(UTC-03:00)Greenland", value: "-3"},
            {text: "(UTC-03:00)Cayenne，Fortaleza", value: "-3"},
            {text: "(UTC-03:00)Montevideo", value: "-3"},
            {text: "(UTC-03:00)El Salvador", value: "-3"},
            {text: "(UTC-02:00)协调世界时-02", value: "-2"},
            {text: "(UTC-02:00)Mid-Atlantic States", value: "-2"},
            {text: "(UTC-01:00)得角群岛", value: "-1"},
            {text: "(UTC-01:00)Azores", value: "-1"},
            {text: "(UTC)Dublin，Edinburgh，Lisbon，London", value: "0"},
            {text: "(UTC)Casablanca，Monrovia，Reykjavík", value: "0"},
            {text: "(UTC)协调世界时", value: "0"},
            {text: "(UTC+01:00)Tripoli", value: "1"},
            {text: "(UTC+01:00)Amsterdam,Berlin,Bern,Rome,Stockholm,Vienna", value: "1"},
            {text: "(UTC+01:00)Belgrade，Bratislava，Pudapest，Ljubljana，Prague", value: "1"},
            {text: "(UTC+01:00)Brussel，Copenhagen，Madrid，Paris", value: "1"},
            {text: "(UTC+01:00)Sarajevo，Skopje，Warsaw，Zagreb", value: "1"},
            {text: "(UTC+01:00)Windhoek", value: "1"},
            {text: "(UTC+01:00)The West Side of Central Africa", value: "1"},
            {text: "(UTC+02:00)Beirut，Damascus，Eastern Europe，Harare，Tshwane", value: "2"},
            {text: "(UTC+02:00)Helsinki，Kiev，Riga，Sofia，Tallinn，Vilnius", value: "2"},
            {text: "(UTC+02:00)Cairo，Athens，Bucharest", value: "2"},
            {text: "(UTC+02:00)Jerusalem，İstanbul", value: "2"},
            {text: "(UTC+03:00)Amman，Baghdad，Königsberg，Minsk", value: "3"},
            {text: "(UTC+03:00)Kuwait，Riyadh，Nairobi", value: "3"},
            {text: "(UTC+03:30)Tehran", value: "3.5"},
            {text: "(UTC+04:00)Abu Dhabi，Muscat", value: "4"},
            {text: "(UTC+04:00)Yerevan，Baku，T'bilisi，Port Louis", value: "4"},
            {text: "(UTC+04:00)Moscow，Saint Petersburg，Volgograd", value: "4"},
            {text: "(UTC+04:00)Kabul", value: "4"},
            {text: "(UTC+05:00)阿什哈巴德，Tashkent", value: "5"},
            {text: "(UTC+05:00)Islamabad，Karachi", value: "5.5"},
            {text: "(UTC+05:30)Madras，Calcutta，Mumbai，New Delhi", value: "5.5"},
            {text: "(UTC+05:30)Sri Lanka Standard Time", value: "5.5"},
            {text: "(UTC+05:45)Kathmandu", value: "5.75"},
            {text: "(UTC+06:00)Actaha，Dhaka，Yekaterinburg", value: "6"},
            {text: "(UTC+06:30)Yangon", value: "6.5"},
            {text: "(UTC+07:00)Bangkok，Ha Noi，Jakarta", value: "7"},
            {text: "(UTC+07:00)Novosibirsk", value: "7"},
            {text: "(UTC+08:00)Beijing，Chongqing，Hong Kong，Urumuqi", value: "8"},
            {text: "(UTC+08:00)Kula Lemper，Singapore，Perth，克拉斯诺亚尔斯克", value: "8"},
            {text: "(UTC+08:00)Taipei，Ulaanbaatar", value: "8"},
            {text: "(UTC+09:00)Seoul，Osaka，Sapporo，Tokyo", value: "9"},
            {text: "(UTC+09:00)Irkutsk", value: "9"},
            {text: "(UTC+09:30)阿尔莱德，达尔文", value: "9.5"},
            {text: "(UTC+10:00)Brisbane，Guam，Port Moresby", value: "10"},
            {text: "(UTC+10:00)Hobart，Canberra，Melbourne，Sydney，Yakutsk", value: "10"},
            {text: "(UTC+11:00)Vladivostok", value: "11"},
            {text: "(UTC+11:00)Solomon Islands，New Caledonia", value: "11"},
            {text: "(UTC+12:00)Auckland，Wellington，Feiji，Magadan", value: "12"},
            {text: "(UTC+12:00)协调世界时+12", value: "12"},
            {text: "(UTC+13:00)Nuku'alofa，Samoa", value: "13"}],
        EditMeetingMinutes: "Edit Meeting Minutes",
        ShareMeetingVideo: "Forward Meeting Recordings",
        ShareMeetingPublic: "Publish",
        shareEditVideoText: "Share Something",
        AttendeeStatus: [
            {text: "Accept", value: "1"},
            {text: "Reject", value: "0"},
            //{text: "待定", value: "2"},
        ],
        ErrorMessage: {
            ERROR_CODE_50501: "预约会议时长超过24小时",
            ERROR_CODE_50502: "预约会议开始时间小于当前时间",
            ERROR_CODE_50503: "预约会议失败",
            ERROR_CODE_50701: "密码错误",
            ERROR_CODE_50703: "获取帐号产品状态欠费",
            ERROR_CODE_50704: "获取帐号产品状态过期",
            ERROR_CODE_50705: "获取帐号产品状态禁用",
            ERROR_CODE_50706: "主持人不能同时进入多场会议",
            ERROR_CODE_50707: "入会失败",
            ERROR_CODE_50708: "会议结束时间小于当前时间",
            ERROR_CODE_50709: "会议不存在",
            ERROR_CODE_50710: "会议已结束",
            ERROR_CODE_50711: "在会议开始时间前45分钟入会",
            ERROR_CODE_50712: "主持人正在会中",
            ERROR_CODE_50713: "参会人正在会中",
            ERROR_CODE_50714: "会议已锁定",
            ERROR_CODE_50715: "超方",
            ERROR_CODE_50716: "站点被禁用",
            ERROR_CODE_50717: "用户入会站点不正确",
            ERROR_CODE_50718: "邮箱和密码不匹配",
            ERROR_CODE_50720: "会议已取消",
            ERROR_CODE_50721: "会议未开始",
            ERROR_CODE_50722: "会议解锁失败",
            ERROR_CODE_50724: "billingcode异常",
            ERROR_CODE_50725: "会议加锁失败",
            ERROR_CODE_50726: "会议不存在",
            ERROR_CODE_50727: "临时会议id创建失败",
            ERROR_CODE_50728: "预约会议，会议表不存在",
            ERROR_CODE_50801: "编辑会议失败",
            ERROR_CODE_50802: "要变更的会议已过期",
            ERROR_CODE_50803: "要变更的会议开始时间小于当前时间",
            ERROR_CODE_50804: "要变更的会议已开始不允许变更会议",
            ERROR_CODE_50805: "要变更的会议不存在",
            ERROR_CODE_50806: "要变更的会议已结束",
            ERROR_CODE_50901: "取消会议失败",
            ERROR_CODE_50902: "要取消的会议不存在",
            ERROR_CODE_50903: "要取消的会议正在召开",
            ERROR_DEFAULT: "请求失败，请重试"
        },
        CreateMeetingLoading: "正在操作，请稍后！",
        Subject: "主题",
        Notice: "请输入会议主题，主题不能超过30个字",
        GroupTime: "会议时间和与会者",
        MeetingAddress: "会议地点",
        CreateMeeting: "新建日程",
        uploadMeetingData: "上传会议资料",
        unuploadMeetingData: "还没有上传任何会议资料",
        cycleMeeting: "您安排了一场周期会议",
        CreateRecurrentMeetingByMe: "您安排了一场会议",
        invitedToCycleMeeting: "邀请您加入周期会议",
        invitedToMeeting: "邀请您加入会议",
        acceptCycleMeeting: "接受了您的周期约会邀请",
        acceptMeeting: "您接受了会议邀请",
        meetingAccepted: "接受了您的会议邀请",
        refuseMeeting: "您拒绝了会议邀请",
        meetingRefused: "拒绝了您的会议邀请",
        updateMeetingByYou: "您变更了会议信息",
        updateMeeting: "变更了会议信息",
        forwardMeetingByYou: "您转发了{1}的会议邀请",
        forwardYourMeeting: "转发了您的会议",
        forwardMeetingToYou: "转发了会议邀请给您",
        HostName: "主持人",
        changeTimeZone: "更换时区",
        repeatCycle: "重复周期",
        repeatCycleItem: [{text: "不重复", value: "1"}, {text: "重复", value: "0"}],
        addBatchUser: "批量添加"
    },
    Update: {
        Title: "Please Update Bee to Use This Application",
        NewVersionTitle: "Bee Has New Updates. Update Now",
        Ignore: "Ignore",
        GiveUp: "Abort",
        Update: "Update",
        Updating: "Updating...",
        TipsTitle: "Reminder",
        GiveUpTips: "If You Abore Update, You Can't Use Bee.  Want To Giv Up?",
        NewFeatures: "New Features",
        Name: "Bee",
        UpdateFail: "Failed to Update",
        UpdateFailTips: "Update Failed. Please choose Manual Update Instead.",
        DownloadSelf: "Manual Update"
    },
    SettingUpdate: {
        Title: "Check Update",
        Cancel: "Cancel",
        Update: "New Update Available",
        UpdateWords: "The Latest Version Is ",
        UpdateNow: "Update Now",
        Confirm: "OK",
        NoUpdate: "You Have Installed The Latest Version",
        NoVersion: "No Update Available",
        UpdateFailed: "Failed to Check Update.  Please Try Again Later."
    },
    ForgetPassword: {
        Tips: "The Verification Code Will Be Sent to Your Mobile via SMS. Please Check.",
        AccountPlaceHolder: "Input Account ID",
        VerifyCodePlaceHolder: "Input Verification Code",
        Cancel: "Cancel",
        Ok: "OK",
        SendMessage: "Send Verification Code via SMS",
        Resend: "Resend",
        MessagePlaceHolder: "Input Verification Code",
        PasswordPlaceHolder: "Input New Password",
        PasswordAgainPlaceHolder: "Inut New Password Again",
        NeitherEmpty: "账号或验证码不能为空",
        NeitherNull: "账号或验证码不能为空格，请输入正确信息",
        NeedMessage: "短信验证码不能为空",
        Redo: "账号获取出错，请重新操作",
        SendTipOne: "短信验证码已经发送到您的手机",
        SendTipTwo: "上，请在下框中输入验证码。 如果未收到短信验证码，请点击重新发送。",
        Forbidden: "此账号禁止修改密码",
        LdapAccount: "You Are Using LDAP-enabled Account, Please Update Password on Your Company Server",
        WrongAccount: "Account ID Error",
        UserNotExist: "The User Is Not Existed",
        WrongCode: "验证码错误",
        ServiceException: "服务器异常，稍后再试",
        FiveTimes: "You Have Request to Send 5 Times Verification Codes. If You Still Don't Receive SMS, Please contact Your System Admin.",
        Hours: "You Have Request 3 Times Verification Codes, Please Apply It Again One Hour Later",
        NumberNotExist: "The Mobile Phone Number Not Existed",
        FunctionForbidden: "此账号禁止使用忘记密码功能",
        ContactIT: "Please Contact Your IT Department to Reset Your Password",
        Failed: "数据获取失败,稍后再试",
        PasswordRulesOne: "密码必须由8-20个字符组成，区分大小写",
        PasswordRulesTwo: "密码必须由8-20个数字和字母组成，区分大小写",
        PasswordRulesThree: "密码必须由8-20个数字,符号与字母组成，区分大小写",
        EnterAgain: "验证码错误，请重新输入",
        CaptchaFailed: "您的验证码已经失效，请您重新申请",
        GetAgain: "验证码错误，请重新获取",
        SetFailed: "设置密码失败",
        NotTheSame: "The New Password Can't Be Same As Previous One"
    },
    ConfirmSetPassword: {
        Title: "Notification",
        Text: "Congratulation! You Have Updated Password.  Please Login Again!",
        Ok: "OK"
    },
    Feedback: {
        Title: "Feedback",
        PlaceHolder: "Please Provide Your Feedback (Less Than 200 Words)",
        UploadLog: "Upload Log",
        Cancel: "Cancel",
        Ok: "OK",
        Prompt: "Notification",
        EnterTip: "Please Input Your Feedback",
        FailedTip: "Failed to Zip Your Log",
        NetworkProblem: "Upload Log Failed. Please Check Your Network Status",
        Thanks: "Thank You For Your Feedback",
        FailedSend: "Send Failed. Please Check Your Network Status"
    },
    ResetPassword: {
        Title: "Reset Password",
        Description: "密码中字符区分大小写，长度必须为8-20位",
        OldPassword: "Old Password",
        NewPassword: "New Password",
        PasswordAgain: "Input Again",
        OldPasswordPlaceHolder: "Input Old Password",
        NewPasswordPlaceHolder: "Input New Password",
        PasswordAgainPlaceHolder: "Input New Password Again",
        Cancel: "Cancel",
        Ok: "Success",
        CapsLock: "Caption Key Locked",
        NotEmpty: "旧密码或新密码不能为空",
        PasswordTip: "密码不能为空格，请重新输入",
        NotMatch: "两次输入密码不一致，检查后重新输入",
        SetFailed: "新密码设置失败",
        WrongOldPassword: "旧密码错误",
        NotThreeTimes: "密码不能与前3次设置的密码相同",
        NotFiveTimes: "密码不能与前5次设置的密码相同",
        NotTenTimes: "密码不能与前10次设置的密码相同",
        NoRepeat: "密码不能与之前设置重复",
        NotNull: "密码不能为空",
        PasswordLength: "The Length of Keyword Is 8 - 20 Degrees",
        PasswordComplexity: "密码复杂度要求8-20位数字和字母组合",
        PasswordRule: "密码复杂度要求8-20位数字、符号和字母组合"
    },
    Emotion: {
        EmotionTag: "[表情]",
        Smile: "Smile",
        Unhappy: "Unhappy",
        Anger: "Angry",
        Blink: "Blink",
        DontKnow: "Don't Know",
        Stunned: "Stunned",
        Laugh: "Lauch",
        Hoho: "呵呵",
        Happy: "Happy",
        Secret: "Secret",
        Sad: "Sad",
        FullJoy: "Full of Joy",
        Sickly: "Sick",
        CanNotSay: "Can't Say",
        ShutUp: "Shut Up",
        StickingTongue: "吐舌头",
        Ponder: "Ponder",
        Sleepy: "Sleepy",
        Doubt: "Doubt"
    },
    SingleChat: {
        PersonalInformation: "Personal Information",
        GroupChat: "Start Group Chatting",
        Me: "You",
        ExternalChat: "外部聊天"
    },
    GroupChat: {
        MyDiscussion: "My Group",
        Chat: "Chat",
        ChatFile: "Chat File",
        ExternalChat: "外部聊天",
        Me: "You",
        Notification: "Notification",
        FileDelete: "The Files Has Been Deleted",
        FileIsDelete: "下载失败,该文件已被删除",
        Contain: "Contains:",
        Delete: "Delete",
        Invitation: "Invitaion",
        Join: "Join",
        GroupChat: "Group Chat",
        Project: "Project",
        CloudChat: "文件库",
        DelGroupChat: "Leave Group",
        DelProject: "Leave Project",
        DelCloudChat: "移出文件库",
        Exit: "Exit",
        EndGroupChat: "Finished",
        IMe: "You Will",
        IBy: "You Will Be",
        By: "by",
        UpdateI: "Updated",
        Avatar: "Avatar",
        ModifyI: "Modify",
        GroupName: "Group Name",
        updateDir: "{1}更新了一个文件夹",
        updateFile: "{1}更新了一个文件",
        deleteDir: "{1}刪除了文件夹'{2}'",
        deleteFile: "{1}刪除了文件'{2}'",
        moveDir: "{1}将文件夹'{2}'移动到【{3}】",
        moveFile: "{1}将文件'{2}'移动到【{3}】",
        renameDir: "{1}将文件夹'{2}'重命名为'{3}'",
        renameFile: "{1}将文件'{2}'重命名为'{3}'"
    },
    MessageBox: {
        SaveFile: "保存文件",
        AllFile: "所有文件",
        openFileFail: "打开文件失败",
        cloudLoadLimit: "您没有权限操作此文件.",
        cloudLoadFail: "文件库加载失败无法操作.",
        cloudLoadLoading: "正在初始化文件库,请稍后重试.",
        fileIdNotExist: "文件被删除了或文件不存在",
        LocalSpaceNotEnough: "本地磁盘空间不足.",
        notForward: "您没有权限转发此文件.",
        notFileInfo: "文件不存在或已经删除.",
        notFileInfoDir: "文件夹不存在或已经删除.",
        notPermission: "您没有权限进行当前文件操作.",
        notRelationGroup: "当前文件库没有绑定讨论组.",
        Notification: "提示",
        Known: "知道了",
        OK: "确定",
        open: "打开",
        openDir: "打开文件夹",
        saveAs: "另存为",
        receive: "接收",
        download: "下载",
        cancel: "取消",
        saveCloud: "存到云盘",
        viewCloud: "点击查看",
        view: "查看",
        updateFile: "更新了文件",
        updateFileDir: "更新了文件夹",
        comment: "评论",
        forward: "转发",
        cloudFilePreviewer: "预览",
        gkNotServer: "未开通够快服务",
        gkAccountOff: "账号已被禁用",
        gkExpire: "所属企业已到期",
        gkToKenFail: "token验证失败",
        GkNotPermission: "没有操作权限",
        GkArgError: "请求参数错误",
        gkConnectFail: "连接服务器失败"
    },
    Comment: {
        DownLoad: "下载",
        Forward: "转发",
        NoComment: "还没有任何评论",
        More: "查看更多评论",
        WriteComment: "写评论...(1-200)",
        CommentSendFail: "评论消息发送失败",
        EnterSend: "按Enter键发送",
        Sending: "发送",
        Open: "打开",
        OpenFail: "打开文件失败",
        Notification: "提示",
        Known: "知道了",
        SaveCloud: "存到云盘"
    },
    Code: {
        Unnaming: "Unnamed Snippet",
        SendCode: "Send Code",
        SelectLanguage: "Choose Snippet Language Type",
        CodeErrorPrompt: "Illegal Snippet Name",
        AddCode: "Add Snippet",
        PleaseInputCode: "Add Snippet Name",
        AddDescription: "Add Description for Easily Reading",
        Cancel: "Cancel",
        Ok: "OK"
    },
    Setting: {
        Title: "Settings",
        Common: "General",
        AutoStart: "Open Bee Automatically When Windows Starts",
        IsTop: "Put Bee on Top of Window",
        VoiceRemind: "开启新消息提醒声音",
        Bubble: "新消息弹出提示气泡",
        SelectVoice: [
            {text: "Ringtone 1", value: "01.amr"},
            {text: "Ringtone 2", value: "02.amr"},
            {text: "Ringtone 3", value: "03.amr"},
            {text: "Ringtone 4", value: "04.amr"},
            {text: "Ringtone 5", value: "05.amr"},
            {text: "Ringtone 6", value: "06.amr"},
            {text: "Ringtone 7", value: "07.amr"},
            {text: "Ringtone 8", value: "08.amr"},
            {text: "Ringtone 9", value: "09.amr"},
            {text: "Ringtone 10", value: "10.amr"},
            {text: "Ringtone 11", value: "11.amr"},
            {text: "Ringtone 12", value: "12.amr"}
        ],
        Safe: "Safe",
        PasswordTips: "Please Update Password Periodically For Safely Usage",
        Remind: "Until Next Updates",
        Day: "Days",
        PasswordModify: "Change Password",
        KeyBoard: "Shortcut Key",
        SendMessage: "Send Message",
        ScreenShots: "Screen Shot",
        OpenMainPage: "Open Main Page",
        Meeting: "Calendar",
        TimeZone: "Time Zone",
        Date: "Date Display Mode",
        TimeShow: "Time Display Mode",
        TimeInterval: "Time Length",
        MeetingTime: "Default Meeting Length",
        Others: "Others",
        Bee: "Bee",
        ServiceTerms: "Service Terms",
        Feedback: "Feedback",
        Default: "By Default",
        SettingUpdate: "Check Updates",
        DefaultTip: "Notification",
        ConfirmDefault: "Are You Sure to Reset All Settings to Default Value?确定要将所有设置项恢复为系统默认值？",
        Cancel: "Cancel",
        Confirm: "OK",
        EnterKeyBoard: "Please Input The New Shortcut Key",
        SelectMessage: [
            {text: "Enter", value: "0"},
            {text: "Ctrl+Enter", value: "1"}
        ],
        SelectTime: [
            {text: "24 Hours", value: "0"},
            {text: "12 Hours", value: "1"}
        ],
        SelectTimeInterval: [
            {text: "15 Minutes", value: "15"},
            {text: "30 Minutes", value: "30"},
            {text: "1 Hour", value: "60"}
        ],
        SelectMeetingTime: [
            {text: "0.5 Hour", value: "30"},
            {text: "1 Hour", value: "60"},
            {text: "1.5 Hours", value: "90"},
            {text: "2 Hours", value: "120"},
            {text: "2.5 Hours", value: "150"},
            {text: "3 Hours", value: "180"}
        ],
        Account: "Account",
        Logout: "Quit",
        Cloud: "云盘",
        Setting: "设置",
        LogoutTips: "You Can't Receive All New Messages If You Quit Bee.  Are You Sure to Quit Now?",
        IllegalShortcuts: "The Shortcut Key Is Illegal",
        ConflictOpen: "Please Reset The Shortcut Key Because It Conflicts with Main Window Settings",
        ConflictScreen: "Please Reset Screen Shot Short Cut Key Because It Conflicts with The Current Settings",
        ServiceContent: "全时服务条款由全时云商务服务股份有限公司（以下简称为“全时”）与任何购买或开立全时账户的个人或实体（包括但不限于任何雇员、独立承包商、被邀请人或上述人员的代理人），及任何访问或使用本协议中的网站、服务和/或软件的其他个人或实体，包括任何会议的参加者，无论参与者是否作为会议发起人或主持人（以下统称为“您”或“用户”），共同签订。</p>" +
        "<p>您同意遵守本协议及其中的全时隐私保护政策，通过创建账户或以其它方式访问或使用本协议中的网站、软件和服务（不只是浏览网站）。</p><p>在安装软件、建立账户或以其它方式使用服务之前，请仔细阅读本协议。请留存协议副本。</p>" +
        "<p>如果您是试用用户、享受免费服务的基本用户或测试版用户，请特别关注本协议末尾适用于本协议中的网站、软件和服务的试用、免费基本使用或测试的第46、47和48条的内容。</p><p>全时可能会随时修订本协议。您能否继续使用本协议中的网站、软件或服务，取决于本协议当时的有效版本中的规定。</p>" +
        "<p>若不同意本协议的条款与条件，请勿访问本协议中的网站、安装本协议中的软件或使用本协议中的服务。</p><h2>1、定义</h2><p>本协议中涉及的术语定义如下（在协议其它部分不再定义）：</p>" +
        "<p>(1).“关联方”是指全时直接或间接控股全时的母公司或子公司，与全时具有公共股权的任何实体（不论共有人全部、大部分或少部分持有），以及上述母公司、子公司或实体的管理人员、董事、雇员、顾问、代理、代表、合资企业或合资伙伴。<br>(2).“协议”是指服务条款和隐私保护政策。<br>" +
        "(3).“会议”统指由本协议中的网站、软件和服务主办和/或传送的特定的网络会议，以及所有数据、数据包、信息、通讯或其它材料传送、复制、上传、转发、控制、下载、记录（不论是否与全时功能或任何安装或单机设备或其它介质记录）或与会议相关的任何其它内容，包括您提供的内容。<br>" +
        "(4).“内容”是指通过本协议中的网站、软件和服务传播、复制、上传、传送、控制、下载、录制（不论是通过全时功能录制，还是通过任何其它安装的或单机的设备或介质）或提供（无论是否使用登录信息）的任何数据、数据包、信息、通讯或其它材料，包括但不限于文件、文章、副本、录音剪辑、漫画、电脑程序、设计、图标、插图、图像、标识、多媒体、照片、声音、文字、商标、短片、个人身份和肖像、录音及任何其它口头、书面或电子表现形式或作品。<br>" +
        "(5).“全时联系界面”是指本协议中的网站、软件和服务的构成部分，这个构成部分允许用户制作和维护联系人列表、向联系人或选择群组发送弹出消息或进行文字聊天，并与他们交换实时状态信息，传输文件，参与相关活动。<br>" +
        "(6).“人”是指任何个人或法人实体。<br>(7).“个人身份信息”是指由全时收集或拥有的可以识别或可用于识别用户的任何信息。<br>(8).“隐私保护政策”是指全时隐私保护政策规定的所有条款和条件，可在任何时间生效，参见 www.quanshi.com。<br>" +
        "(9).“服务请求”是指由您发起、全时接受的任何书面或电子命令，或让您访问和使用本协议中的网站、软件和服务的任何其它方法，不论您有无向全时支付费用。<br>(10).“服务”是指，依据特定情况，" +
        "（i）您通过免费测试账户、免费基本账户、免费试用账户或付费账户使用或将使用的网络会议功能，如相关的服务请求中所描述；（ii）您使用或本协议中的网站和软件提供给您的任何其它功能，包括但不限于全时联系界面服务和音频会议服务。<br>" +
        "(11).“网站”是指 www.quanshi.com、其子域名及后续站点。<br>(12).“软件”指专有软件和所有相关文件以及您使用的或由全时提供给您用于访问网站和使用服务的其它材料。</p><h2>2、用户许可的授予</h2>" +
        "<p>基于您持续遵守本协议的条款和条件，全时授予您个人的、非排他性的、不可转让的、可撤销的许可，在有效期内，您可以：</p><p>（i）出于个人或商业用途访问和使用本协议中的网站，不可下载（页面缓存除外）或修改网站内容，或网站的任何部分，<br> （ii）安装软件（只限于目标代码和可执行代码格式），<br> （iii）访问和使用服务（“许可”）。一旦本协议期满或因其它原因终止后，许可将立即自动终止。</p>" +
        "<h2>3、网站、软件和服务的所有权</h2><p>本协议中的网站、软件和服务提供使用许可，而不是出售，仅供您根据本协议条款及授予的许可使用。全时保留关于或体现在本协议中的网站、软件和服务中的所有权利和权益，包括但不限于知识产权、技术、软件和与之相关的副本。您在此同意立即制作 G–net 自行决定其必要性的任何进一步的文件，以法律或商业文件的形式，完善或保留这种所有权，包括但不限于（如适用的话）确保您的员工和/或承办商也这样做。</p>" +
        "<h2>4、标志的所有权</h2><p>所有与本协议中的网站、软件和服务有关的品牌名称、图形、标识、产品名称、服务标志、域名、商标和商品名称（以下统称“商标”）均归全时或其关联公司所有。全时与其关联方保留所有权利和权益，包括商标的所有知识产权。您不得使用其中的任何商标。</p>" +
        "<h2>5、内容许可</h2><p>您在此同意，专为本协议中的网站、软件和服务提供非排他性的、全球性的、免权利金的、已全付的、可转让的许可，允许全时主机、高速缓存、记录、复制、展示、传送、上传、传输、控制、下载、录制和分发关于您使用本协议中的网站、软件和服务方面的内容。一旦本协议期满或因其它原因终止，本许可将立即自动终止，除非根据我们的数据存储政策，该内容被全时存储或以其它方式保留。</p>" +
        "<h2>6、关于内容的免责声明</h2><p>G–net不验证或认可任何内容。您对所有内容全权负责，包括所有内容备份副本的制作与保存。对于内容的删除或准确性、储存失败、无法传输或接收（不论是否通过本协议中的网站、软件和服务），或源于任何会议或其它涉及本协议中的网站、软件或服务使用的其它通讯方式的安全性、隐私、存储或传输，全时不承担任何责任。</p>" +
        "<h2>7、网站、软件和服务使用限制</h2><p>您同意不进行反编译、反汇编、反向工程、翻译或以其它任何方式试图了解本协议中的网站、软件或服务的源代码。除非本协议中明确规定，您不可直接或间接创建、分配、复制、制造衍生产品、传递、分发、租赁、借贷、修改、抵押、出租、出售、再授权、分时共享、利用或以其它方式转让本协议中的网站、软件或服务，或其任何部分或权利。不可删除任何商标、版权声明或其它所有权或标记，不可更改或添加商标、版权声明或本协议中的网站、软件或服务中包含的标记或其它专有权利。除非事先与全时签署书面协议，您不得转售本协议中的网站、软件、服务或其任何部分，或作为其代理作出任何行为。</p>" +
        "<h2>8、用户声明、保证和承诺</h2>您特此作出如下的声明、保证和承诺，您知晓和了解全时及其关联方将相信这些声明、保证及承诺，这些声明、保证及承诺在协议期内是真实无误的：<br><dl><dt>(1).网站、软件和服务的使用。</dt><dd>1). 您拥有签订本协议并履行本协议的行为所需要的所有权利、权力和授权，包括（a）使用应用软件（第三方或其它，产生协议规定的“内容”）的有效许可，以及（b）提交和使用“内容”的无限制权限。除非您有权提交和使用与会议有关的个人身份信息和其它信息（无论属于您、其他会议参加者或任何第三方），否则不允许向本协议中的网站提交此类“内容”或信息，或以其它任何涉及本协议中的网站、软件或服务的方式使用您的“内容”。</dd><dd>2). 访问和使用本协议中的网站、软件和服务可能需要向第三方支付费用（包括但不限于电话费、通话费或互联网服务提供商费用，或与互联网服务相关的收费或税款，包括由政府机构征收的任何销售或使用税）。上述所有费用或税款，均由您独自承担。对于安装软件或访问或使用本协议中的网站、软件或服务可能需要的任何设备，全时不负责提供。</dd><dd>3). 如要访问和使用本协议中的网站、软件和服务（除了仅浏览本协议中的网站公开内容之外），您需要提供电子邮件地址并创建登录ID账号和密码（统称“登录信息”）。关于登录信息的任何事宜，均由您全权负责。登录信息必须保密，不得透露给任何第三方。关于您对登录信息的使用、分发、披露或管理，全时不承担任何义务或责任。尽管有上述规定，若登录信息不符合本协议的条款，G–net可能会要求您更改登录信息。您同意，全时可以不经调查，针对您的任何登录信息采取行动。对于您的登录信息或通过任何方式接收的通知、文件中含有的任何声明或陈述，我们不承担任何调查其真实性或评估其价值的责任。任何人，只要使用您的登录信息，即被视为已经被授权使用本协议中的网站、软件和服务从事交易，因此，其所做出的所有交易均被视为已经过您的授权和批准。对于此类交易所导致的任何索赔或损害，全时不承担任何责任。</dd><dt>(2).内容。</dt><dd>1). 您是所有“内容”的所有者、获得授权的被许可方或授权用户。</dd><dd>2). 您不可公布、张贴、上传、记录、链接或以其它方式分发或传送如下任何内容：(a) 涉嫌侵犯或违反全时或任何其他人的版权、专利、商标、服务标记、商业名称、商业秘密、域名或其它知识产权，或任何人的公开权或隐私权的内容；(b) 违反任何适用法律、法规、条例或规定的内容（包括但不限于关于反歧视、出口管制、虚假广告或不公平竞争方面的适用法律、法规）；(c) 宣传、诱唆、包括或含有侮辱性的、诽谤的、过于暴力的、骚扰性的、不恰当的、猥亵的、淫荡的、猥琐的、淫秽的、色情的、亵渎的、恐吓性的、庸俗的或其它令人反感的或非法的材料；(d) 对未成年有害的内容；(e) 包含清除程序、损坏文件、时间炸弹、木马、病毒、蠕虫或任何其它类似数据、程序或软件，可能会破坏、侵占、截留或干扰其他人的数据、资料、所有权或系统，或者可能对本协议中的网站、软件或服务造成损害或干扰；(f) 违反事实、具有误导性和不准确的内容；(g) 倡导、协助、煽动、唆使、推广或以其它方式鼓励暴力或任何非法活动的内容；(h) 企图误导他人关于您的身份、信息来源或其它消息的来源，假冒或以其它方式歪曲您与全时或任何其他人的隶属关系，或者涉及虚假内容、具有误导性或不准确；或(i) 含有您无权准许全时收集和处理的信息。</dd><dt>(3).遵守法律。</dt><dd>1). 根据本协议，包括但不限于第5条（内容许可），您有权将全时及关联方授予您或应当授予您的所有许可和其它权利转授给第三者所有权（包括第三方知识产权）。</dd><dd>2). 您应当熟悉和遵守任何可能禁止您访问或使用本协议中的网站、软件或服务，或参加会议，或可能限制或规范这类参与或使用行为的法律，否则您将承担全部责任。</dd><dd>3). 不得将本协议中的网站、软件或服务用于任何非法目的。</dd><dd>4). 同意遵守所有适用的地区、国家和国际法律法规，包括但不限于有关拦截、监控或录制讯息、隐私和数据保护及公开展示或表演等方面的法律。您进一步同意，无论本协议还是全时的任何其它权利或补救措施，均不意味着全时必须行使任何权利或采取任何补救措施以保护您或任何其他人，虽然全时有权自行决定这样做。</dd><dt>(4).信用卡信息。</dt><dd>如果使用信用卡支付，您提供给全时的信用卡资料应当在任何时候都是真实、准确和完整的。您应当保证，通过信用卡向全时支付的款项将由您的信用卡公司负责兑现。根据本协议，包括但不限于第10条（信用卡授权），若有任何款项无法兑现，您须负责支付所有款项。</dd><dt>(5).使用限制。</dt><dd>您承认并同意，任何未经授权的对本协议中的网站、软件或服务的使用、复制或分发，是法律明确禁止的，并可能导致严重的民事责任和刑事处罚。我们将在最大程度上对违反者予以起诉。您同意不进行（包括但不限于）以下任何构成未经授权使用的行为：</dd><dd>1). 未经授权，企图进入或使用本协议中的网站、软件或服务，或访问与本协议中的网站、软件和服务相连接的其它账户、计算机系统或网络，无论是通过非法访问、破译密码或任何其它手段；</dd><dd>2). 伪造或删除任何版权管理信息，如作者属性、法律或其它适当的通知或专有名称，或软件来源标志或上传文件包含的其它材料；</dd><dd>3). 通过任何手段获取或试图获取非本协议中的网站、软件和服务有意公开的一切资料或信息；</dd><dd>4). 参与系统提取任何数据或数据字段，包括但不限于电子邮件地址；</dd><dd>5). 扰乱、妨碍或阻止其他人使用和享受本协议中的网站、软件或服务；</dd><dd>6). 侵犯全时或任何第三方的权利，包括但不限于侵犯、诽谤、诈骗、骚扰、跟踪、威胁或以其它方式侵犯（如隐私权和公开权）全时或任何第三方的合法权利；</dd><dd>7). 使用虚假或假名返回电子邮件地址的任何的 G - net 域名;</dd><dd>8). 以全时的名义销售任何商品或服务（包括宣传和出价购买或销售商品或服务，或以任何方式暗示全时推荐这些产品和服务或全时与其相关），除非全时对于此类活动给予事先书面同意；</dd><dd>9). 使用本协议中的网站、软件或服务的方式可能会损害、破坏或以其它方式干扰或扰乱本协议中的网站、软件或服务或与之相连的任何网络，或使其超载或无法使用；或</dd><dd>10). 访问或使用本协议中的网站、软件和服务的方式可能会毁坏或损害全时服务器或连接到全时服务器的任何网络，或使其超载或无法使用。</dd><dt>(6).全时联系界面。</dt><dd>您承认并同意，全时联系界面允许全时在任何特定时间获取并记录您的联系人信息、电脑使用情况以及其它信息，并且全时可以使用和维持此类信息：（1）供全时自己之用，（2）向您提供营销信息，（3）在您进行试用、免费基本使用或使用测试版期间，向您的联系人提供营销信息，以及（4）依据适用法律或政府要求随时披露给第三方（包括政府官员或根据法庭指令）。</dd></dl>" +
        "<h2>9、期限，延期及终止。</h2><dl><dt>(1).期限。本协议的有限期限（“期限”）规定如下：</dt><dd>1). 试用，免费基本使用，以及测试版使用。如果您已经订阅了本协议中的网站、软件和服务进行试用（第50条“试用”）、测试版使用（第51条“测试版使用”），或免费基本使用（第52条“免费基本使用”），本协议期限的起始时间为：（i）全时接受您试用、免费基本使用或测试版使用服务请求的当日上午12:00，或（ii）您第一次进行本协议中的网站、软件和服务试用、免费基本使用或测试版使用的当日上午12:00（不论全时是否首先接受您的服务请求）。上述情况下，全时授予试用、免费基本使用或测试版使用的时限结束时，本协议随即终止，按照第9条（3）项提前终止。</dd><dd>2). 付费使用。除订阅本协议中的网站、软件和服务进行试用、测试版使用或免费基本使用的情况之外，本协议期限的起始时间为：（i）全时接受您服务请求的当日上午12:00，或（ii）您第一次使用本协议中的网站、软件和服务的当日上午12:00（不论全时是否首先接受您的服务请求），不论您是否已经向全时支付任何费用。上述情况下，本协议有效期持续至相应服务请求中指定的日期，须根据第9条（2）项自动延期或根据第9条（2）项提前终止。</dd><dt>(2).自动延期。</dt><dd>在试用、免费基本使用和试用版使用期限结束时，您可以选择通过付费延长本协议有效期。如果您选择不付费续约，本协议将于有效期最后一天晚上11:59（格林尼治标准时间加上8小时）终止。在付费有效期（即：除试用、免费基本使用和测试版使用期限之外的任何有效期，无论您是否向全时支付任何款项）的最后一天，本协议将自动延期，新的有效期于翌日（以下简称“续期日期”）上午12:00（格林尼治标准时间加8小时）开始，并且将通过您的信用卡收取费用，直至本协议在第9条（3）项规定的续约日期之前终止。您将承担每个续期的所有订购费及其它费用。如果不希望续订，您有权利和义务终止该协议。</dd><dt>(2). 终止方式。</dt><dd>1). 如果您不接受第47条所述的本协议的更新或修订，本协议将自动终止。</dd><dd>2). 在本协议期满前，如果出现下列情形，全时可以通过发送终止通知到您登录信息中填写的E-mail地址（该通知在全时发送之后即刻生效）或通过第34条（1）项中规定的其它方式，终止本协议以及您访问的本协议中的网站、软件和服务的许可：<br> A.您违反第2节（用户许可的授予）、第3条（网站、软件和服务的所有权）、第4条（商标所有权）或第8条（用户声明，保证和承诺）中的一项或多项规定；或<br> B.违反本协议的任何其它规定，并且在收到全时通知的五个工作日之内，未能消除或者补救该违约行为;或<br> C．全时可以依据其唯一和排他性的判断，出于安全原因，决定终止您访问或使用本协议中的网站、软件或服务，以保护全时免于责任或保持本协议中的网站、软件或服务继续正常高效运行和一贯质量。</dd><dd>3). 您可以随时以任何理由或无理由终止本协议，只要在续期前至少提前二十四（24）小时通过网站向全时提供电子通知，或在续期前至少五（5）个工作日内保证全时收到书面通知；但是，鉴于您访问和使用本协议中的网站、软件和服务的权利将在我们收到上述通知后立即终止，您应付给全时的所有款项必须已足额缴付，以确保能够有效终止。</dd><dt>(4).终止之后</dt><dd>1). 无论是由于协议期满、未自动续约或任何其它原因，本协议一旦终止，您必须立即停止使用本协议中的网站（浏览公开内容除外）、软件和服务。本协议一旦终止，您访问账户中及服务处理情况的任何内容的权利随即终止。</dd><dd>2). 本协议一经终止，全时有权删除与您使用本协议中的网站、软件和服务相关的全部数据文件，包括但不限于与您的“内容”“全时联系界面”或“个人身份信息”相关的任何数据文件。</dd><dd>3). 如果您已经支付本协议中的网站、软件和服务费用，除因遭受不可抗力因素影响之外，不论因其他何种原因本协议提前终止，全时概不退款；</dd><dd>4). 终止之后，根据G-net隐私保护政策，全时有权保留您的个人身份信息，以与您保持联络，提供信息及其产品和服务。</dd></dl>" +
        "<h2>10. 信用卡授权。</h2><dl><dt>(1).如果通过本协议中的网站订购服务并且选择通过信用卡付款，只有全时承认的有效信用卡才可用于支付。如需退款，全时会将款项返还至同一信用卡账户。协议有效期内并且直到所有款项已全部如期支付，您在此授权全时根据本协议从您提供的信用卡中收取所有款项，包括但不限于所有付款额、税费及额外费用。如果您的服务请求包括音频会议，那么您在此授权全时基于您实际使用音频会议的分钟数或在服务请求中约定的服务套餐，按月从您的信用卡中扣除音频会议服务的拖欠款项。</dt><dt>(2). 如果该卡无法通过验证、属于无效卡或因其它原因不被接受，您访问或使用本协议中的网站、软件和服务的权利可能会被全时延迟、暂缓或取消，恕不另行通知，且全时可能会开出发票要求您付款。您同意将信用卡的更新信息及时知会全时。如果主卡支付被拒绝，全时可能还会要求您提供一个辅信用卡账号。此外，一经要求，您应当立即通过信用卡向全时支付款项，款项可根据具体情况撤销。</dt><dt>(3). 关于费用的问题必须知会我们的收账部门，根据第34条(2)项，在结算期满后的九十(90) 天之内通知收账部门。您同意全时可以提交账单以供处理，即使信用卡似乎已经到期。除非相应的“服务请求”中有特别规定，所有价格都必须以人民币支付，并且价格中不包括相应税款、关税和类似收费，这些费用将由你单独支付。您同意承担政府机构或代收机构向服务（包括但不限于所有全时音频会议服务）征收的所有相应税费。</dt></dl>" +
        "<h2>11. 电子通讯。</h2><p>本协议中的网站、软件和服务均由全时以电子化的形式进行并提供。全时可能通过电子化的形式，就本协议中的网站、软件和服务方面的所有事宜与您进行沟通。基于互联网（包括电子邮件）的通信安全易受全时控制之外的很多因素的影响。我们不保证任何电子通信的安全或隐私，对于此类通讯对您或任何第三方造成的损害，我们不承担任何赔偿责任。</p>" +
        "<h2>12. 隐私保护政策。</h2><p>您承认已经获知和阅读本协议中的隐私保护政策。如果隐私保护政策与本协议存在抵触，以本协议为准。全时可能会不定期地对隐私保护政策进行修订。更新修订后的隐私保护政策将在网站上公布，以供您查阅。请定期查看本协议中的网站主页上的“全时使用条款”链接，以获知现行的隐私保护政策。您承认并同意，G–net可以接收、分享和传送您在本协议中的网站、软件和服务（包括但不限于个人身份信息）的使用中产生的信息，无论是与电信运营商和政府机构等相关服务提供商召开的会议或以其它方式所产生的信息。对于上述信息接收、共享或传送，全时不对您承担任何责任。收集的与会者信息（不论会议是由您或其它任何与会者发起），包括但不限于个人身份信息，将按照我们现行的隐私保护政策，以您的名义、在您的控制下，存储在我们的服务器上；除非这些信息适用于您自己的隐私保护政策，此时本隐私政策不适用于参会者信息的收集和存储。</p>" +
        "<h2>13. 个人身份信息披露。</h2><p>除协议中隐私保护政策或第22条（调查）、第50条（试用）、第51条（试用版使用）及第52条（免费基本使用）另有规定，全时不会将您的个人身份信息透露给任何第三方。但是，全时可自行决定（但并无义务）随时监控或审查您对本协议中的网站、软件和服务的访问和使用。全时可随时在不进行事先通知的情况下，自行决定终止访问或使用张贴或提交资料的网站页面，或披露任何有关您访问和使用本协议中的网站、软件和服务的任何信息或您张贴、提交的任何内容，只要全时认为有必要，包括但不限于遵守适用法律、法规、法律程序或政府要求。您同意，在任何会议上披露任何有关您自己或者任何组织的个人身份信息时，或在网站或任何会议上张贴或以其它方式提交任何资料时（包括个人身份信息），会格外谨慎。您提供给全时的所有必要的注册信息必须是最新的、完整和准确的。如有更改，必须迅速、及时地知会全时。如果你对本协议中的网站、软件和服务的访问和使用涉及密码限制访问您的敏感信息（如客户名单和合同条款），然后通过访问或使用本协议中的网站、软件和服务和设立账户，您同意由全时显示和存储此类信息，并承担未授权访问此类信息的所有风险。</p>" +
        "<h2>14. 记录和隐私特性。</h2><p>本协议中的网站、软件和服务可能允许您记录会议相关内容，收集和利用有关您和其他与会者的身份信息，包括但不限于个人身份信息，如作为会议或会议记录一部分而显示、处理、储存或传送的肖像、姓名或语音等。某些地区的法律规定，在拦截、监测和/或记录个人通讯之前，应当给予通知或征得同意。另外，一些地区的法律限制对个人身份信息的采集、存储和使用。您同意遵守所有适用的法律，在使用本协议中的网站、软件或服务之前获得所有必要同意并作出必要披露，包括但不限于使用记录功能时。您已认可，在会议中或通过其它方式与其他人沟通时，您的部分或全部“内容”可能会被记录并被其它用户传送。当参加会议时，对于您的摄像机视野范围，您将全权负责。其他与会者通过您的相机看到的任何信息都有可能会被与会者记录和传播，并且被全时记录和存储。这些记录可能是由全时功能单元、您计算机中的嵌入式设备，或照相机、手机等独立装置完成的。无论是作为主持人、参与者或其他人员，对于您访问和使用会议中或者通过访问本协议中的网站、软件和服务传递的任何第三方的资料和信息（包括个人身份信息），您将承担全部责任，全时及其关联方对此概不负责。</p>" +
        "<h2>15. 内容访问和存储。</h2><dl><dt>(1).本协议中的服务是通过自动的方式向您提供的，即通过相关的软件工具上传内容，完成与会议或其它活动有关的传输、下载等操作。除下述情况外，全时不会访问、查看或听取任何内容：1）本协议（包括隐私保护政策）规定准许的情况，或2）需要维护或提供本协议中的网站、软件和服务，包括但不限于：(A) 响应服务请求； (B) 在您的要求下，恢复服务中断时的适当内容； (C)符合法律要求或遵守法律程序，全时本着诚信善意原则认为必要或适当时； (D) 检测、阻止或以其它方式解决欺诈、安全或技术问题；(E) 实施本协议，包括对潜在违反行为的调查，第22节 (调查)中予以详述；或 (F) 如果您要求全时担任会议、报告或其它事件的主机、制作者、主持人或促进者，作为本协议中的网站、软件和服务的一部分。</dt><dt>(2). 应会议主持人或其指定的个人之要求（会议主持人或其他个人，称为“演示者”），本协议中的网站、软件和服务可能会收集某些个人身份信息及其它信息，包括但不限于：1）您观看的会议幻灯片；2）您对会议演示者发起的调查的回应；3）本协议中的网站、软件和服务用户或用户与演示者之间的实时“聊天”；4）您的姓名、地址、电话号码、电子邮件地址和其他个人身份资料，以及5）任何其他个人身份信息或您提供给本协议中的网站、软件和服务的其它信息，无论您自愿主动提供还是应演示者之要求。会议演示者可能看到上述信息，且应演示者要求或者作为本协议中的网站、软件和服务的自动功能，诸如“聊天”或您的提问等信息可能会与其他用户共享。</dt><dt>(3). 对于演示者是否会使用您的个人身份信息以及通过何种方式使用，全时无法控制，并对此不承担任何责任。全时不会预先筛选用户使用本协议中的网站、软件和服务提供或以其它方式提交的信息。全时可能会收集关于您使用本协议中的网站、软件和服务的某些信息，诸如网络服务提供商的名称和互联网协议地址；访问本协议中的网站、软件和服务的时间；访问的页面；您通过哪个网址链接到本协议中的网站。全时使用该信息为本协议中的网站、软件和服务提供支持，并根据您显示的通讯首选项及本协议规定，向您发送有关G –net以及其产品和服务的讯息。</dt></dl>" +
        "<h2>16.非中国居民。</h2><p>全时收集的与本协议有关的个人身份信息可能会在中华人民共和国或全时或其关联企业的设施所在的任何其它国家进行存储和处理。您同意将个人身份信息转移到您的国籍所在国或居住国之外。</p>" +
        "<h2>17.危险环境或高风险活动。</h2><p>本协议中的网站、软件和服务不适用于任何危险或高风险的环境或活动，或需要自动防故障装置或控制的任何情况，包括但不限于核设施、飞机导航或通讯系统、空中交通管制、维持生命仪器或重症监护设施、救援或紧急情况、手术、武器系统的操作，或因会议或本协议中的网站、软件或服务的故障而可能直接或间接导致死亡、人身伤害或重大财产损失的任何其它环境或情况。在不限制前述规定或任何限制的适用性、或载于本协议其它地方的全时免责声明的前提下，全时特此声明对任何前述使用或任何类似使用不承担任何明示或暗示保证的责任。您承认并同意，由您、代表您或在您的指令下（不论明示或暗示）对本协议中的网站、软件和服务的任何与上述使用或任何类似使用有关的使用，应独立进行，完全由您自己承担风险，并且全时及其关联企业对任何情况下的这种使用都不承担任何责任。</p>" +
        "<h2>18.停机时间。</h2><p>虽然我们尽力将停机时间降至最低，但由于定期维护或其它原因，本协议中的网站、软件和服务有时仍然可能无法使用。在停机超过四十八（48）小时的情况下，除非发生以下条款中规定的情形，全时将退还您已支付的停机期间的款项：</p>" +
        "<p>（1）如果在您的有偿使用期限中，连续停机时间为三十（30）天或更长的时间，全时将退还您为该期限所支付的全部金额，可退款的最长服务期限为三个月。<br> （2）如果在您的有偿使用期限中，连续停机时间超过五（5）天，但少于三十（30）天，则全时将退还三十（30）天服务期限的款项。<br> （3）如果在您的有偿使用期限中，连续停机时间为五（5）天或更短的时间，则按照停机发生的天数退还款项，可退款的最长服务期限为三（3）天。</p>" +
        "<p>停机退款将在发生停机的服务期限到期后的三十（30）个营业日之内存入与您的账户关联的信用卡中。</p><p>由于下列情形之一造成的停机将不予发放第18条中所述的停机退款：</p>" +
        "<p>1）定期维护（停机维护通知将提前公布在网站上靠近用户登录点的地方和/或通过电子邮件发送到包含在您的主要登录信息里的电子邮件地址；<br />2）在第39条（不可抗力）中规定的任何情形；<br />" +
        "3）由于与您的个人计算机硬件、软件、网络、网络设置或安全、或您的互联网服务供应商相关的问题或任何其它类似的问题而导致您无法连接或使用本协议中的网站、软件或服务。</p>" +
        "<p>与任何非付费使用（包括但不限于任何试用、免费基本使用或测试使用）有关的停机将不予发放第18条中所述的停机退款。</p>" +
        "<h2>19.无担保责任。</h2>" +
        "<p>全时并不声明或担保任何内容的准确性或可靠性。您承认，您对任何（您或其他人的）内容的信赖都完全由您自己承担风险。任何用户发布在网站上的任何内容仅代表了发布该内容的用户的观点，并不代表全时的观点。</p>" +
        "<h2>20.第三方网站的链接。</h2>" +
        "<p>本协议中的网站可能包含将您带到本协议中的网站以外的其它网站的链接（统称为“链接网站”）。链接网站是由全时为方便起见而提供给您的，这些链接并不意味着全时对任何链接网站予以担保。全时对链接网站没有控制权。在任何情况下，全时或其关联企业对任何链接网站的任何内容、产品或服务都不承担任何责任。您承认并同意，您访问任何链接网站的风险应完全由您自己承担。您承认并同意，全时对任何链接网站的内容、链接网站中所包含的任何链接、或链接网站的任何更改或更新都不承担任何责任。您进一步承认并同意，全时对从任何链接网站收到的任何形式的传输（如网上广播）不承担任何责任。</p>" +
        "<h2>21.调查。</h2>" +
        "<p>全时一般不监视与本协议中的网站、软件或服务相关的用户活动。但是，如果全时察觉您事实上或可能违反本协议的任何条款，包括但不限于第8条（用户声明、保证和承诺），全时有权调查这些事实上或可能的违约行为，并且全时可以自行决定立即终止本协议（包括本协议授予的许可），并同步通知用户终止本协议，或者全时可以变更、修改或删除全部或部分内容，并无须事先通知您。如果在经过此类调查后，全时认为犯罪活动已经发生或正在发生，全时有权将该事项呈送给并配合全部各相关执法机关。在涉及任何此类调查时，全时有权在适用法律禁止的范围内，向执法或其他政府官员披露全时根据自己的判断认为有必要或适当的任何我们在您使用本协议中的网站、软件和服务时所掌握的关于您的资料信息（包括但不限于个人身份信息）。</p>" +
        "<h2>22.版权侵权通知。</h2>" +
        "<p>如果您侵犯他人的知识产权，全时将自行决定在适当情况下终止本协议（包括本协议授予的许可和其它权利）。全时将调查版权侵权通知并采取适当的行动。如果您认为任何原著作品的使用或复制构成版权侵权，并且该侵权与本协议中的网站、软件和服务有关，请向我们提供以下所有信息：</p>" +
        "<p>1）经授权代表版权利益所有人行事的个人的电子或亲笔签名；<br />" +
        "2）对您声称受到侵权的版权作品的描述；<br />" +
        "3）对您声称其相关材料构成侵权的会议的描述；<br />" +
        "4）您的地址、电话号码和电子邮件地址；<br />" +
        "5）您作出书面声明，表示您有充分的理由认为该有争议的使用未经版权所有人、其代理人或法律授权；<br />" +
        "6）您作出书面声明，表示上述通知中的信息是准确的，并且您是版权所有人或者经授权作为版权所有人的代表。所有此类通知都应按照第31条规定的程序发送给全时。</p>" +
        "<h2>23.受限制的访问和使用。</h2>" +
        "<p>某些国家或某些人不能使用本协议中的网站、软件和服务。全时可自行随时更改其特性和组成，理由包括但不限于为了符合现行适用法律和法规。全时有权在任何时间以任何理由（包括但不限于为了符合适用法律）拒绝任何国家、管辖区、地理区域或个人访问和使用本协议中的网站、软件和服务。</p>" +
        "<h2>24.对全时的保障。</h2>" +
        "<p>您在此同意维护、保护和保障全时及其关联企业免受由下列情形引起或与下列情形有关的全部索赔、债务、损害赔偿或费用（包括但不限于律师和专家证人的费用、成本费及其它开支）的损害：</p>" +
        "<p>1）您或使用您的登录信息的任何人（不论该使用是否经您授权）使用或访问本协议中的网站、软件或服务，包括全时接触界面；<br />" +
        "2）您或使用您的登录信息的任何人（不论该使用是否经您授权）事实上或被指控违反本协议或适用法律，包括但不限于任何出口管制法律；<br />" +
        "3）您或使用您的登录信息的任何人（不论该使用是否经您授权）事实上或被指控侵犯或侵害任何人的任何知识产权、专利权、隐私权或其它权利；<br />" +
        "4）您对会议参加者或本协议中的网站、软件和服务的任何其他用户的通讯信息、肖像、姓名、声音或其它个人身份信息予以录制；<br />" +
        "5）针对产品责任、特定目的之不适用性的索赔或指控，或由您的产品使用引起或与您的产品使用有关的任何其它索赔和指控；<br />" +
        "6）您与任何其它会议参加者或本协议中的网站、软件和服务的其他用户之间发生的任何争端；<br />" +
        "7）支付给全时的任何信用卡资金的撤回；<br />" +
        "8）您的疏忽或故意的不当行为。此外，根据本协议，为了访问和使用本协议中的网站、软件和服务而购买或开设账户者应促使所有通过其账户访问本协议中的网站、软件和服务的其他人遵守本协议的条款及条件，同意支付本协议项下的所有款项，并对其本人或第三方在其全时账户中进行的所有活动负责，包括但不限于由本协议中的网站、软件或服务的任何用户导致的费用支付，还应维护、保护和保障全时及其关联企业免受由于其他人的使用而引起或与该使用有关的全部索赔、债务、损害赔偿或费用（包括但不限于律师和专家证人的费用、成本费及其它开支）的损害。</p>" +
        "<h2>25.保证免责声明。</h2>" +
        "<p>本协议中的网站、软件和服务，以及全部会议，都是按“现有”、以“现状”和“连同本身具有的一切瑕疵”予以提供的，没有任何其它形式的保证。在适用法律允许的最大范围内，全时特此声明，对所有关于本协议中的网站、软件、服务或任何会议的明示、暗示或法定的声明、保证、条件及任何类型的职责（如有）不承担任何责任，包括但不限于任何适售性、特定目的之适用性、准确性、可用性或相容性、具纯熟技术或无过失性能。本协议中的网站、软件和服务是商业产品，其应用性质是商业性而不是消费性的。在接受本协议时，您承认，在适用法律允许的最大范围内，消费者保护法并不适用于您对本协议中的网站、软件和服务的使用，也不适用于本协议涵盖的或根据本协议完成的任何交易。</p>" +
        "<h2>26.责任限制。</h2>" +
        "<dl>" +
        "<dt>除非适用法律另有要求，否则您同意，除了您在合理使用本协议中的网站、软件或服务时实际发生的直接经济损失（总体统称为“直接损失”）以外，所有的损害赔偿都不包含在您依据本协议可能从全时获得的追偿中，并且在任何情况下，您将无权获得任何损害赔偿。如果证明有任何直接损害，赔偿金额应限定在您于发生索赔前支付给全时的三个月期限内的实际服务金额之内。在不限制上述规定的前提下，您同意免除以下损害赔偿：<br />" +
        "(1).由于您没有能力使用本协议中的网站、软件或服务或访问数据、信息（包括但不限于个人身份信息）或内容而造成的全部损害赔偿。</dt><dt>(2).由下列情形引起或与下列情形有关的任何其它索赔的全部损害赔偿：</dt><dd>1）任何第三方于本协议中的网站、软件或服务中或通过本协议中的网站、软件或服务作出的声明或行为；</dd><dd>2）与供应商或其他第三方的任何交易；</dd><dd>3）对您的传输、材料、信息（包括但不限于个人身份信息）或其它数据的任何未经授权的访问和修改；</dd><dd>4）任何已发送或已收到、或者未发送或未收到的信息；</dd><dd>5）任何链接网站；</dd><dd>6）您访问或使用、或没有能力访问或使用任何链接网站。</dd><dt>(3).由于与您的个人计算机硬件、软件、网络、网络设置或安全、或您的互联网服务供应商相关的问题或任何其它类似的问题而导致您无法连接或使用本协议中的网站、软件或服务，从而引起或造成与此关联的全部损害赔偿（包括但不限于停机时间的赔偿）。</dt></dl>" +
        "<h2>27.暗示保证的免责。</h2>" +
        "<p>本协议赋予您具体的法定权利。您还应具有各国不同的其它法定权利。有些国家或管辖区不允许暗示保证的免责或对暗示保证的持续期限的限制，因此本协议中包含的限制可能不适用于您。在许可范围内，全时的所有暗示保证的期限被限制在九十（90）天之内。</p>" +
        "<h2>28.对使用或内容不负责。</h2>" +
        "<p>您同意，全时或其任何一个关联企业对任何内容或对全时的访问、记录、存储或其它使用都不承担任何责任，包括但不限于：</p>" +
        "<p>1）已发送、接收、持有、发布的或与本协议中的网站、软件或服务的任何方面有关的任何内容；<br />" +
        "2）已发送但对方没有接收到的任何内容；<br />" +
        "3）由您或任何其他人对内容所作的任何访问或修改；<br />" +
        "4）使用本协议中的网站、软件和服务发送的，或包含于本协议中的网站、软件和服务中的任何内容；<br />" +
        "5）任何诽谤、非法、淫秽、攻击性或威胁性的内容；<br />" +
        "6）您或任何其他人在使用本协议中的网站、软件或服务时的行为；<br />" +
        "7）对其他人的权利的任何侵权，包括但不限于隐私权、知识产权或数据保护。全时对第三方服务不提供保证并且不承担任何类型的责任或义务，包括但不限于由于本协议中的网站、软件和服务与任何第三方服务不相容而造成的任何责任。您同意，您不会使全时及其任何一个关联企业对任何第三方服务负有责任或义务。</p>" +
        "<h2>29.对错误不承担责任。</h2>" +
        "<p>本协议中的网站、软件和服务可能包括技术性差错或其它差错、不精确性和/或排印错误。全时可随时自行决定对本协议中的网站、软件和服务作出变更，包括但不限于其中列出的所有产品或服务的价格和描述，并无须事先通知您或其他人。本协议中的网站、软件和服务可能是过时的，并且全时不承诺随时更新网站、软件和服务。全时对所有客户信息或材料的误用、丢失、修改或失效不负有任何责任。</p>" +
        "<h2>30.使用风险由您全部承担。</h2>" +
        "<p>对本协议中的网站、软件和服务的使用，以及对其中任何信息或材料的下载或其它使用，将完全由您自行决定和承担全部风险，并且，您理解，您对您的计算机系统的任何损害或任何数据丢失或由于此类活动造成的其它损害负有全部责任。对于其他人无论是否在您知情的情况下使用您的登录信息而使您遭受的任何损失，全时概不负责。全时对以下情形不承担任何责任：您或任何第三方以任何方式修改了软件，或者由于您通过任何硬件配置、平台或操作系统来使用本协议中的网站、软件和服务而造成的任何故障，包括但不限于由于与您的个人计算机硬件、软件、网络、网络设置或安全、或您的互联网服务供应商相关的问题或任何其它类似的问题而导致您无法连接或使用本协议中的网站、软件或服务，从而引起或造成与此关联的任何故障。</p>" +
        "<h2>31.通知。</h2>" +
        "<dl><dt>根据本协议，您和全时应互相提供所有必需的信息，如下所示：</dt><dt>(1).对您的通知。通知应按照以下任一方式发送给您：</dt><dd>1）通过电子手段发送到与您的账户关联的电子邮件地址，并且在全时发送后即视为已送达；</dd><dd>2）通过打印出来的第一类邮件发送到您的登录信息中所包含的地址，并且在邮件寄出五（5）天后视为已送达。</dd><dt>(2).对全时的通知。除了本协议明确允许的以电子手段通知全时的方式外，还可以如下方式通知全时：</dt><dd>1）经挂号、签名和附回执的第一类邮件，或快递邮件；</dd><dd>2）需交付签名的隔夜快递；这两种方式的通知均应发送到本协议中的网站上指明的主要营业地点，收件人为总裁。您发送的所有通知应在全时的授权代表实际收到并签字后被视为送达。</dd></dl>" +
        "<h2>32.豁免。</h2>" +
        "<p>您在此特许全时及其关联企业免受由以下情形引起或与以下情形有关的每类和每种性质的全部（实际和衍生的）索赔、要求和损害赔偿的损害：</p>" +
        "<p>1）您使用本协议中的网站、软件和服务主持或参加会议或应用于本协议未规定或未允许的其它目的；<br />" +
        "2）由您参与的任何会议或该会议中的任何内容引起或与之有关的任何交易、事件、事故、伤害或其它损害。</p>" +
        "<h2>33.管辖法律及管辖地。</h2>" +
        "<p>本协议应受中华人民共和国法律管辖并依据中华人民共和国法律进行解释。本协议的每一方都同意，由本协议引起或与之有关的任何法律程序应提交到本协议的签订地中华人民共和国北京市的具司法管辖权的法院。特此，每一方均在法律允许的最大范围内不可撤销地放弃其现在或以后反对该法院的审判地点的权利。</p>" +
        "<h2>34.持续有效性。</h2>" +
        "<p>即使本协议取消、终止、期满终止或中止，本协议中的第1条（定义）、第3条（网站、软件和服务的所有权）、第4条（标志的所有权）、第6条（关于内容的免责声明）、第9条第4款（终止之后）、第11条（电子通讯）、第17条（危险环境或高风险活动）仍将持续有效。</p>" +
        "<h2>35.权利的保留。</h2>" +
        "<p>全时保留本协议未明确地授予的所有权利。</p>" +
        "<h2>36.无效。</h2>" +
        "<p>如果本协议的任何部分被有司法管辖权的法院认定为无效的或不能强制执行的，则该无效或不能强制执行的条款应由最大限度上符合原条款旨意的有效、可强制执行的条款取代，并且协议中剩余的条款将继续发挥充分效力。</p>" +
        "<h2>37.不放弃权利。</h2>" +
        "<p>除非经相关的全时授权官员亲笔签字的非电子化书面明确同意，否则我们未能行使或强制执行本协议中的任何权利或条款的事实并不构成对该权利或条款的放弃。</p>" +
        "<h2>38.不可抗力。</h2>" +
        "<p>全时对其合理控制范围之外的任何事件造成的未能履约或延迟履约不承担任何责任，包括但不限于意外事故、天灾、黑客活动、民变、地震、禁运、传染病、爆炸、火灾、洪水、自然力量、战事、恶意行为、全国紧急状态、革命、暴乱或战争，以及起因于设备或软件或电信故障、电力故障、网络故障、第三方服务供应商（包括国际服务和电信供应商）故障的服务中断。</p>" +
        "<h2>39.无第三方受益人。</h2>" +
        "<p>本协议的受益人只包括您、全时及其关联企业。本协议没有第三方受益人。</p>" +
        "<h2>40.转让。</h2>" +
        "<p>未经全时事先书面同意，您不得按合同或依法律规定或其它方式转让本协议、协议中的任何权利或义务。全时可转让本协议，并无须通知您或经过您的同意。</p>" +
        "<h2>41.完整协议。</h2>" +
        "<p>本协议（包括合并在完整协议中的隐私权政策）构成全时与您之间关于本协议中的网站、软件和服务的完整协议和谅解，并且取代了全时与您之间关于该事项的其它预先或同一时间的书面、口头或非电子化沟通、协议、谅解和提议。</p>" +
        "<h2>42.可接纳性。</h2>" +
        "<p>本协议的一个打印版本和以电子形式发送给您的任何通知，在根据或与这个协议相关的司法或行政程序中都是可接纳的，同时，以打印形式生成和维护的其它商业文件也具有同等程度的可接纳性，并受相同条件约束。</p>" +
        "<h2>43.更新和修正。</h2>" +
        "<p>全时可随时修正本协议中的条款（包括合并在协议中的隐私权政策）。如果您不接受修正，本协议将终止。本协议将自动地合并和纳入全部增加的条款、修正、特点、修改、补充、更新和其它功能或相关信息，包括但不限于全时在协议期限中依据任何附加条款和条件提供或使其顾客普遍可用的与本协议中的网站、软件或服务有关的可用性、内容、特点、功能、安全、存储和其它信息（统称为“更新”），包括由全时提供的应用于此类更新的任何附加费和费用。您特此授权并同意，全时可根据我们在适用时间内有效的标准操作程序，随时自动和善意地传输、访问、安装和提供更新，并无须另行通知您或取得您的同意。全时没有义务（并且本协议中没有任何条款可以解释为要求全时）创造、提供或安装更新。您对本协议中的网站、软件和服务的访问和使用将永远遵守最新版本的服务条款和隐私权政策，以及在使用时公布在网站上的全部规定和准则。请定期点击网站主页上的“全时使用条款”链接，查看当前的服务条款和隐私权政策。尽管第47条中有相反规定，如果全时在网站上公布修正后的条款，该修正条款仍将自动生效，且在公布到网站上后，应立即合并到本协议里，并且取代协议中与之不一致的任何条款和条件。在上述修正条款公布出来后，您对本协议中的网站、软件或服务的使用表示您同意自生效时间起接受该修正条款的约束。因此，您同意定期访问本协议中的网站查看本协议当前的条款和条件（包括隐私权政策）。</p>" +
        "<h2>44.权力。</h2>" +
        "<p>如果您是代表某个实体签订本协议的个人，您声明并且保证您是在该实体主管部门的授权下签订本协议的，并且该实体受本协议中所有条款和条件的约束。</p>" +
        "<h2>45.标题。</h2>" +
        "<p>本协议中条款的标题仅为方便起见而拟定的，不视为可影响它的结构或解释。</p>" +
        "<h2>46.试用。</h2>" +
        "<p>如果您订购了本协议中的网站、软件和服务的试用，您对本协议中的网站、软件和服务的访问和使用应受下列附加条款和条件的约束，如附加条款和条件与本协议中的条款和条件不一致，则取代本协议中与之不一致的条款和条件：</p>" +
        "<p>（1）作为本协议中的网站、软件和服务的试用者，您访问和使用本协议中的网站、软件和服务的权利受本协议中条款的限制。对本协议中的网站、软件和服务的试用可能由全时在稍后的时间里提供，并且试用版本的特点和功能有所不同，而是否收费由全时全权决定。<br> （2）尽管您在创造自己的登录信息时表示了沟通偏好，您仍然同意，全时可在您的试用期间随时与您联系关于本协议中的网站、软件和服务的事宜。<br> （3）全时有权使用您的个人身份信息，包括但不限于您通过使用本协议中的网站、软件和服务而沟通的第三方的身份。例如，在不限制前述条款的前提下，全时可与您和第三方联系，以提供信息、销售其产品和服务，以及寻求关于本协议中的网站、软件和服务的评论和反馈，并且全时可为了各种营销目的经常向您和第三方发送电子邮件，包括为第三方提供免费试用。<br> （4）您不得出于任何商业或生产目的使用或依赖本协议中的网站、软件或服务。<br> （5）在您的试用期限结束以后，您可以付费订购另一个期限，也可以拒绝这么做。如果您拒绝，全时有权保留您的个人身份信息，以便随时与您联系，向您提供信息、销售其产品和服务。</p>" +
        "<h2>47.测试使用。</h2>" +
        "<p>如果您正在进行本协议中的网站、软件和服务的测试使用，您对本协议中的网站、软件和服务的访问和使用应受下列附加条款和条件的约束，如附加条款和条件与本协议中的条款和条件不一致，则取代本协议中与之不一致的条款和条件：</p>" +
        "<p>（1）您承认，本协议中的网站、软件和服务是“测试版本”，并不代表最终产品，并且，它同样可能包含可能削弱功能或造成系统故障的缺陷、错误和其它问题。<br> （2）您承认：1）全时未公开地宣布本协议中的网站、软件和服务的后续商业版本的可用性；2）全时未向您承诺或保证未来将宣布或使任何人可用到本协议中的网站、软件和服务的后续商业版本；3）全时对您或任何人没有明示或暗示的义务宣布或推出本协议中的网站、软件和服务的后续商业版本或其它版本；4）全时可自行决定是否推出与本协议中的网站、软件和服务相似或一致的产品；5）在随后发布的本协议中的网站、软件和服务的任何商业版本中，可能会或不会提供测试版本中所包含的特点或服务。<br> （3）除了隐私权政策中另有的规定外，全时有权使用您的个人身份信息，包括但不限于您通过使用本协议中的网站、软件和服务而沟通的第三方的身份。例如，在不限制前述条款的前提下，全时可与您和第三方联系，以提供信息、销售其产品和服务，以及寻求关于本协议中的网站、软件和服务的评论和反馈，并且全时可为了各种营销目的经常向您及您的联系人发送电子邮件，包括为您的联系人提供测试使用。<br> （4）您不得出于任何商业或生产目的使用或依赖本协议中的网站、软件和服务。<br> （5）在您的测试使用期限结束以后，您可以付费订购另一个期限，也可以拒绝这么做。如果您拒绝，全时有权保留您的个人身份信息，以便随时与您联系，向您提供信息、销售其产品和服务。</p>" +
        "<h2>48.免费基本使用。</h2>" +
        "<p>如果您申请了本协议中的网站、软件和服务的免费基本使用权限，您访问和使用本协议中的网站、软件和服务时应受下列附加条款和条件的约束，如附加条款和条件与本协议中的条款和条件不一致，则取代本协议中与之不一致的条款和条件：</p>" +
        "<p>（1）作为本协议中的网站、软件和服务的免费基本用户，您访问和使用本协议中的网站、软件和服务的权利受本协议中条款的限制。全时可自行决定随时因故或无故中断您对本协议中的网站、软件和服务的免费基本使用权。另外，全时有权随时改变免费使用基本版的部分或全部特点、功能或可用性。全时对免费基本使用的任何中止和变更不承担责任。<br> （2）尽管您在创造自己的登录信息时表示了沟通偏好，您仍然同意，全时可在您使用免费基本版期间随时就本协议中的网站、软件和服务事宜与您联系。<br> （3）全时有权使用您的个人身份信息，包括但不限于您通过使用本协议中的网站、软件和服务而与之沟通的第三方的身份。例如，在不限制前述条款的前提下，全时可与您和第三方联系，以提供信息、产品和服务，以及寻求关于本协议中的网站、软件和服务的评论和反馈，并且全时可为了各种营销目的经常向您和第三方发送电子邮件，包括为第三方提供免费试用。<br> （4）全时有权自行决定随时在本协议中的网站、软件和服务中放置自己或第三方的广告、水印、连接到第三方网站的链接，或者进行其它任何形式的用户界面变更。<br> （5）全时不针对免费基本版的使用，做任何关于本协议中的网站、软件和服务的可用性或正常运行时间的保证或担保。<br> （6）全时有权终止和删除长达90天未活动的免费基本用户的账户和所有相关的数据及个人身份信息。<br> （7）免费基本使用期限将持续延伸，直到您或全时根据本协议予以终止。<br>" +
        "（8）在您的免费基本使用期限结束以后，全时有权保留您的个人身份信息，以便随时与您联系，向您提供信息，销售其产品和服务或第三方的产品和服务。您可以随时决定退出该计划。</p>" +
        "<p>如果您不同意本协议中的条款与条件，请勿访问或使用本协议中的网站，勿安装本协议中的软件，勿使用本协议中的服务。 </p>",
        GetDetectionFailed: "获取检测设备失败，请稍后重试",
        AVDetection: "音频检测",
        StartAVDetection: "开始检测"
    },
    CreateProject: {
        CreateProjectTitle: "Create Project",
        Ok: "OK",
        PleaseInputName: "Please Input Project Name"
    },
    Profile: {
        SendMessage: "Send Message",
        SendCall: "呼",
        ViewCalendar: "Check Calendar",
        Social: "Workbook",
        Signature: "Personalized Signature",
        Account: "Account",
        Mobile: "Mobile",
        Email: "Email",
        WorkPhone: "Office Phone",
        EmployeeId: "Employee ID",
        Leader: "Leader",
        Colleagues: "Colleagues",
        ProjectCreater: "Project Owner",
        Members: "Members",
        Setting: "Settings",
        ChatSetting: "Chat Settings",
        NoDisturbing: "Mute Notification",
        AddNewMember: "Add New Member",
        ExitGroup: "Leave This Group",
        ExitCloud: "退出文件库",
        ExitProject: "Leave This Project",
        EndProject: "Close This Project",
        RemoveMember: "Move {1} Out of This Group?",
        Prompt: "Notification",
        ConfirmExit: "Leave This Group?",
        ConfirmEnd: "Close This Project?",
        YouBeenRemovedGroup: "您已被移出群聊",
        YouBeenRemovedProject: "您已被移出项目组",
        Include: "Include:",
        Comma: "、",
        AddAttention: "Follow",
        Attentioned: "Following",
        CommonAttention: "互相关注",
        PersonalData: "Personal Information",
        Relationship: "Relationship",
        SendMessage: "Send Message",
        ChangeIcon: "Change Avatar",
        NoticeSize: "1. Supports JPG, PNG, BMP. The File Size Can't Exceed 5 MB",
        NoticeWidth: "2. The Minimum Size of Image Width And Height Should Larger Than 150 Pixels.",
        ChooseIcon: "Choose Icon",
        Previews: "Preview",
        Loading: "Loading...",
        ServerError: "服务器异常",
        ConfirmExitIfInGroupCall: "您当前正在呼中，退出后也将退出呼，是否退出？",
        SaveToAddressBook: "Save to address book"
    },
    ChooseContacts: {
        MembersLimitMessage: "最多选取{1}人，您已经超出人数限制。",
        GetOrgAllMembersExceptionMessage: "Failed to Choose Contacts from Organization Chart",
        ProjectAlreadySelectedMessage: "You Already Choosed This Project",
        ChatAlreadySelectedMessage: "You Already Choosed This Group",
        GroupNotExistsMessage: "Can't Choose Now Because You Are Not in the Group无法选择，您已经不在该项目或群组。",
        SelectedContactsCountButton: "Select ({1} Contact)",
        Search: "Search (Contacts、Projects、Group Chats)",
        MyDepartment: "My Department",
        Ok: "OK(已选0人)",
        FrequentContacts: "Frequent Contacts",
        Contacts: "Contacts",
        Projects: "Projects",
        GroupChats: "Group Chat",
        MyDept: "My Department",
        Org: "Organization",
        Email: "Email Contacts",
        MoreContacts: "More Contacts",
        MoreProjects: "More Projects",
        MoreGroupChats: "More Group Chats",
        Searching: "Searching...",
        PleaseChooseLeftContacts: "Please Choose Contact from Left Side Contact List",
        FailedToGetData: "获取后台数据出错，请稍后再试",
        EmailAddress: "Add Email Address",
        AddEmail: "Add Email Address",
        RegInputEmail: "Please Input Correct Email Address",
        SelectList: "已选列表",
        Tips: "Notification",
        CannotChooseDepart: "You Can't Choose Department When You Forward The Message"
    },
    Cloud: {
        LoadCloud: "正在加载...",
        LoadCloudFail: "糟糕了! 页面加载不成功!",
        DownloadingPrompt: "文件已在下载，请到云盘上下载队列查看",
        RepeatLoadCloud: "重新加载",
        Notification: "提示",
        NotComment: "文件库没有关联讨论组，无法评论!",
        NotGroup: "获取信息失败，请稍后重试!",
        cloudChatTitle: "库讨论设置",
        cloudChatNotDisturb: "消息免打扰",
        setAdmin: "已经成为管理员",
        cancelAdmin: "已经被取消管理员资格",
        GK_ERROR_CODE_401141: "您的帐号未开通云盘功能",
        GK_ERROR_CODE_401142: "您的帐号已被禁用",
        GK_ERROR_CODE_401143: "您的帐号试用期已到",
        GK_ERROR_CODE_401144: "帐号信息认证失败"
    },
    OpenApi: {
        OpenApp: "Open Application",
        OpenApiSendMsg: "Send Message",
        OpenApiClosed: "[Closed]",
        OpenApiFilterAll: "全部",
        OpenApiFilterPending: "待审批",
        OpenApiFilterPended: "已审批",
        OpenApiFilterOther: "其他",
        Comment: "请填写审批意见",
        ApprovePlaceHolder: "请填写审批意见...",
        ApproveTitle: "审批意见",
        ApproveNoEmpty: "请填写审批意见",
        ApproveOverMax: "最多可输入128个字符，您已经超出字数限制！",
        NotSupportSignature: "PC版蜜蜂暂时不支持此功能，请使用手机版添加审批",
        OpenApiDefaultTitle: "审批"
    },
    Bubble: {
        NewMessageTitle: "New Message"
    },
    UserStatus: {
        OnLine: "在线",
        OffLine: "离线",
        InCall: "通话中",
        InMeeting: "会议中",
        InCallMessage: "对方正在通话中，暂时可能不方便回复",
        InMeetingMessage: "对方正在会议中，暂时可能不方便回复",
        OffLineMessage: "对方暂时不在线，如有急事，请用其他联系方式"
    },
    dialPad: {
        input: "输入电话号码",
        ok: "确定",
        cancel: "返回",
        CountryCode: [
            {text: "中国", value: "86"},
            {text: "香港", value: "852"},
            {text: "台湾", value: "886"},
            {text: "澳门", value: "120"},
            {text: "美国", value: "150"},
            {text: "新加坡", value: "180"}
        ]
    },
    IntlTelInput: {
        intlTeldata: [
            {name: "阿富汗", dialCode: "93"},
            {name: "阿尔巴尼亚", dialCode: "355"},
            {name: "阿尔及利亚", dialCode: "213"},
            {name: "美属萨摩亚", dialCode: "1684"},
            {name: "安道尔", dialCode: "376"},
            {name: "安哥拉", dialCode: "244"},
            {name: "安圭拉岛", dialCode: "1264"},
            {name: "南极", dialCode: "672"},
            {name: "安提瓜和巴布达", dialCode: "1268"},
            {name: "阿根廷", dialCode: "54"},
            {name: "亚美尼亚", dialCode: "374"},
            {name: "阿鲁巴", dialCode: "297"},
            {name: "澳大利亚", dialCode: "54"},
            {name: "奥地利", dialCode: "43"},
            {name: "阿塞拜疆", dialCode: "994"},
            {name: "巴哈马", dialCode: "1242"},
            {name: "巴林", dialCode: "973"},
            {name: "孟加拉", dialCode: "880"},
            {name: "巴巴多斯", dialCode: "1246"},
            {name: "白俄罗斯", dialCode: "375"},
            {name: "比利时", dialCode: "32"},
            {name: "伯利兹", dialCode: "501"},
            {name: "贝宁", dialCode: "229"},
            {name: "百慕大", dialCode: "1441"},
            {name: "不丹", dialCode: "975"},
            {name: "玻利维亚", dialCode: "591"},
            {name: "波黑", dialCode: "387"},
            {name: "博茨瓦纳", dialCode: "267"},
            {name: "巴西", dialCode: "55"},
            {name: "英属维京群岛", dialCode: "1284"},
            {name: "文莱", dialCode: "673"},
            {name: "保加利亚", dialCode: "359"},
            {name: "布基纳法索", dialCode: "226"},
            {name: "布隆迪", dialCode: "257"},
            {name: "柬埔寨", dialCode: "885"},
            {name: "科麦隆", dialCode: "237"},
            {name: "加拿大", dialCode: "1"},
            {name: "佛得角", dialCode: "238"},
            {name: "开曼群岛", dialCode: "1345"},
            {name: "中非共和国", dialCode: "236"},
            {name: "乍得", dialCode: "235"},
            {name: "智利", dialCode: "56"},
            {name: "中国", dialCode: "86"},
            {name: "圣诞岛", dialCode: "61"},
            {name: "科科斯（基林）群岛", dialCode: "61"},
            {name: "哥伦比亚", dialCode: "57"},
            {name: "科摩罗伊斯兰", dialCode: "269"},
            {name: "库克群岛", dialCode: "682"},
            {name: "哥斯达黎加", dialCode: "506"},
            {name: "克罗西亚", dialCode: "385"},
            {name: "古巴", dialCode: "53"},
            {name: "塞浦路斯", dialCode: "357"},
            {name: "捷克", dialCode: "420"},
            {name: "刚果民主共和国", dialCode: "243"},
            {name: "丹麦", dialCode: "45"},
            {name: "吉布提", dialCode: "253"},
            {name: "多米尼克", dialCode: "1767"},
            {name: "多米尼加共和国", dialCode: "1809"},
            {name: "迪拜", dialCode: "971"},
            {name: "厄瓜多尔", dialCode: "593"},
            {name: "埃及", dialCode: "20"},
            {name: "萨尔瓦多", dialCode: "503"},
            {name: "赤道几内亚", dialCode: "240"},
            {name: "厄立特里亚", dialCode: "291"},
            {name: "爱沙尼亚", dialCode: "372"},
            {name: "埃塞俄比亚", dialCode: "251"},
            {name: "福克兰群岛", dialCode: "500"},
            {name: "法罗群岛", dialCode: "298"},
            {name: "斐济", dialCode: "679"},
            {name: "芬兰", dialCode: "358"},
            {name: "法国", dialCode: "33"},
            {name: "法属波利尼西亚", dialCode: "689"},
            {name: "加蓬", dialCode: "241"},
            {name: "干比亚", dialCode: "220"},
            {name: "加沙地带", dialCode: "970"},
            {name: "格鲁吉亚", dialCode: "995"},
            {name: "德国", dialCode: "49"},
            {name: "加纳", dialCode: "233"},
            {name: "直布罗陀", dialCode: "350"},
            {name: "希腊", dialCode: "30"},
            {name: "格陵兰岛", dialCode: "299"},
            {name: "格林纳达", dialCode: "1473"},
            {name: "关岛", dialCode: "1671"},
            {name: "危地马拉", dialCode: "502"},
            {name: "几内亚", dialCode: "224"},
            {name: "几内亚比绍", dialCode: "245"},
            {name: "圭亚那", dialCode: "592"},
            {name: "海地", dialCode: "509"},
            {name: "洪都拉斯", dialCode: "504"},
            {name: "中国香港", dialCode: "852"},
            {name: "匈牙利", dialCode: "36"},
            {name: "冰岛", dialCode: "354"},
            {name: "印度", dialCode: "91"},
            {name: "印度尼西亚", dialCode: "62"},
            {name: "伊朗", dialCode: "98"},
            {name: "伊拉克", dialCode: "964"},
            {name: "爱尔兰", dialCode: "353"},
            {name: "以色列", dialCode: "972"},
            {name: "马恩岛", dialCode: "44"},
            {name: "意大利", dialCode: "39"},
            {name: "科特迪瓦", dialCode: "225"},
            {name: "牙买加", dialCode: "1676"},
            {name: "日本", dialCode: "81"},
            {name: "泽西岛", dialCode: "441534"},
            {name: "约旦", dialCode: "962"},
            {name: "哈萨克斯坦", dialCode: "7"},
            {name: "肯尼亚", dialCode: "254"},
            {name: "基里巴斯", dialCode: "686"},
            {name: "南斯拉夫", dialCode: "381"},
            {name: "科威特", dialCode: "965"},
            {name: "吉尔吉斯", dialCode: "996"},
            {name: "老挝", dialCode: "856"},
            {name: "拉脱维亚", dialCode: "371"},
            {name: "黎巴嫩", dialCode: "961"},
            {name: "莱索托", dialCode: "266"},
            {name: "利比里亚", dialCode: "231"},
            {name: "列支敦士敦", dialCode: "423"},
            {name: "立陶宛", dialCode: "370"},
            {name: "卢森堡", dialCode: "352"},
            {name: "利比亚", dialCode: "218"},
            {name: "澳门", dialCode: "853"},
            {name: "马其顿", dialCode: "389"},
            {name: "马达加斯加", dialCode: "261"},
            {name: "马拉维", dialCode: "265"},
            {name: "马来西亚", dialCode: "60"},
            {name: "马尔代夫", dialCode: "960"},
            {name: "马里", dialCode: "223"},
            {name: "马耳他", dialCode: "356"},
            {name: "马绍尔群岛", dialCode: "692"},
            {name: "毛里塔尼亚", dialCode: "222"},
            {name: "毛里求斯", dialCode: "230"},
            {name: "马约特岛", dialCode: "262"},
            {name: "墨西哥", dialCode: "52"},
            {name: "密克罗尼西亚", dialCode: "691"},
            {name: "摩尔多瓦", dialCode: "373"},
            {name: "摩纳哥", dialCode: "377"},
            {name: "蒙古", dialCode: "976"},
            {name: "蒙特塞拉特", dialCode: "1664"},
            {name: "摩洛哥", dialCode: "212"},
            {name: "莫桑比克", dialCode: "258"},
            {name: "缅甸", dialCode: "95"},
            {name: "纳米比亚", dialCode: "264"},
            {name: "瑙鲁", dialCode: "674"},
            {name: "尼泊尔", dialCode: "977"},
            {name: "荷兰", dialCode: "31"},
            {name: "荷属安德列斯群岛", dialCode: "599"},
            {name: "新喀里多尼亚", dialCode: "687"},
            {name: "新西兰", dialCode: "64"},
            {name: "尼加拉瓜", dialCode: "505"},
            {name: "尼日尔", dialCode: "227"},
            {name: "尼日利亚", dialCode: "234"},
            {name: "纽埃", dialCode: "683"},
            {name: "诺福克岛", dialCode: "672"},
            {name: "朝鲜", dialCode: "850"},
            {name: "北马里亚纳群岛", dialCode: "1670"},
            {name: "挪威", dialCode: "47"},
            {name: "阿曼", dialCode: "968"},
            {name: "巴基斯坦", dialCode: "92"},
            {name: "帕劳", dialCode: "680"},
            {name: "巴拿马", dialCode: "507"},
            {name: "巴布亚新几内亚", dialCode: "675"},
            {name: "巴拉圭", dialCode: "595"},
            {name: "祕鲁", dialCode: "51"},
            {name: "菲律宾", dialCode: "63"},
            {name: "皮特肯群岛", dialCode: "870"},
            {name: "波兰", dialCode: "48"},
            {name: "葡萄牙", dialCode: "351"},
            {name: "葡萄牙", dialCode: "351"},
            {name: "波多黎各", dialCode: "1"},
            {name: "卡塔尔", dialCode: "974"},
            {name: "刚果共和国", dialCode: "242"},
            {name: "罗马尼亚", dialCode: "40"},
            {name: "俄罗斯", dialCode: "7"},
            {name: "卢旺达", dialCode: "250"},
            {name: "圣巴特岛", dialCode: "590"},
            {name: "圣赫勒拿岛", dialCode: "290"},
            {name: "圣基茨和尼维斯联邦", dialCode: "1869"},
            {name: "圣卢西亚", dialCode: "1758"},
            {name: "圣马丁岛", dialCode: "1599"},
            {name: "圣皮埃尔和密克隆", dialCode: "508"},
            {name: "圣文森特和格林纳丁斯", dialCode: "1784"},
            {name: "萨摩亚", dialCode: "685"},
            {name: "圣马力诺", dialCode: "378"},
            {name: "圣多美和普林西比", dialCode: "239"},
            {name: "沙特阿拉伯", dialCode: "966"},
            {name: "塞内加尔", dialCode: "221"},
            {name: "塞尔维亚和黑山", dialCode: "382"},
            {name: "塞舌尔", dialCode: "248"},
            {name: "塞拉利昂", dialCode: "232"},
            {name: "新加坡", dialCode: "65"},
            {name: "斯洛伐克", dialCode: "421"},
            {name: "斯洛文尼亚", dialCode: "386"},
            {name: "所罗门群岛", dialCode: "677"},
            {name: "索马里", dialCode: "252"},
            {name: "南非", dialCode: "27"},
            {name: "韩国", dialCode: "82"},
            {name: "南苏丹", dialCode: "211"},
            {name: "西班牙", dialCode: "34"},
            {name: "斯里兰卡", dialCode: "94"},
            {name: "苏丹", dialCode: "249"},
            {name: "苏里南", dialCode: "597"},
            {name: "斯瓦尔巴特", dialCode: "47"},
            {name: "斯威士兰", dialCode: "268"},
            {name: "瑞典", dialCode: "46"},
            {name: "瑞士", dialCode: "41"},
            {name: "叙利亚", dialCode: "963"},
            {name: "中国台湾", dialCode: "886"},
            {name: "塔吉克斯坦", dialCode: "992"},
            {name: "坦桑尼亚", dialCode: "255"},
            {name: "泰国", dialCode: "66"},
            {name: "东帝汶", dialCode: "670"},
            {name: "多哥", dialCode: "228"},
            {name: "托克劳群岛", dialCode: "690"},
            {name: "汤加", dialCode: "676"},
            {name: "特立尼达和多巴哥", dialCode: "1868"},
            {name: "突尼斯", dialCode: "216"},
            {name: "土库曼斯坦", dialCode: "993"},
            {name: "土耳其", dialCode: "90"},
            {name: "英属特克斯和凯科斯群岛", dialCode: "1649"},
            {name: "图瓦卢", dialCode: "688"},
            {name: "乌干达", dialCode: "256"},
            {name: "乌克兰", dialCode: "380"},
            {name: "阿联酋", dialCode: "971"},
            {name: "英国", dialCode: "44"},
            {name: "美国", dialCode: "1"},
            {name: "乌拉圭", dialCode: "598"},
            {name: "美属维京群岛", dialCode: "1340"},
            {name: "乌兹别克斯坦", dialCode: "998"},
            {name: "瓦努阿图", dialCode: "678"},
            {name: "梵蒂冈", dialCode: "39"},
            {name: "委内瑞拉", dialCode: "58"},
            {name: "越南", dialCode: "84"},
            {name: "瓦利斯和富图纳", dialCode: "681"},
            {name: "约旦河西岸地区", dialCode: "970"},
            {name: "西撒哈拉", dialCode: "21228"},
            {name: "也门", dialCode: "967"},
            {name: "赞比亚", dialCode: "260"},
            {name: "津巴布韦", dialCode: "263"}
        ]
    },
    AVdetection: {
        title: "音频检测",
        detectionEquipment: "无",
        stepbutton: {
            prevStepBtn: "上一步",
            nextStepBtn: "下一步",
            finishBtn: "完成"
        },
        stepName: {
            speaker: "扬声器",
            mike: "麦克风",
            video: "摄像头"
        },
        speakeContent: {
            useingEquipmentTip: "你正在使用的音频输出设备是：",
            clickDetectionBtnTip: "请点击“播放测试音”按钮试听",
            DetectionBtn: "播放测试音",
            StopDetectionBtn: "停止播放",
            errorTip: "如果没有听到声音，可以尝试以下方法解决：</br> 1.调节系统音量并检查是否静音</br>  2.检查扬声器电源和开关，调节设备上的音量旋钮</br> 3.检查扬声器或二级插头是否插入正确的扬声器插孔"
        },
        mikeContent: {
            useingEquipmentTip: "你正在使用的音频输入设备是：",
            clickDetectionBtnTip: "对麦克风说话，音量指示条将显示现在的录音状态：",
            errorTip: "如果听不到录音，可以尝试以下方法解决： </br>1.调节系统音量并检查录音设备是否启用 </br>2.如果麦克风有开关，检查是否将其打开 </br>3.检查麦克风是否连接到正确的插孔"
        },
        vedioContent: {
            useingEquipmentTip: "你正在使用的视频输入设备是：",
            errorTip: "一般摄像头问题，可以尝试以下方法解决： </br>1.检查摄像头连接是否正确 </br>2.检查是否有其他应用正在使用此设备"
        },
        tips: {
            jumpDetectionTip: "要跳过音频视频设备检测吗？"
        }
    }
};